### ISSUE TITLE
Vagrant rsync should support --copy-dirlinks

### ISSUE THREAD

**Issue by purpleidea** [pradels/vagrant-libvirt#113]
When running vagrant provision, the rsync is invoked with a static set of options. Currently that is:

<pre>
# from vagrant-libvirt/action/sync_folders.rb
            command = [
              "rsync", "--del", "--verbose", "--archive", "-z",
              "--exclude", ".vagrant/",
              "-e", "ssh -p #{ssh_info[:port]} #{proxycommand} -o StrictHostKeyChecking=no -i '#{ssh_info[:private_key_path]}'",
              hostpath,
              "#{ssh_info[:username]}@#{ssh_info[:host]}:#{guestpath}"]
</pre>

For files that use symlinks that point outside of the rsync-ed folder, you'll get dead symlinks.

I propose that --copy-dirlinks be added, but only as an option. This means that if you'd like to use this option, there's a way to set it from the vagrantfile.

If you can guide me on the correct way to glue in the options in the vagrantfile, I'm happy to write the patch. I think it would be useful to specify it on a per-type-of-thing sync-ing sort of way.

Let me know,
James

**Comment by pronix** [comment]
http://docs.vagrantup.com/v2/synced-folders/rsync.html

**Comment by purpleidea** [comment]
@sciurus I don't need this anymore, and @pronix points out it seems to be configurable now with the options args. I didn't test, but it's okay to close :)
