### ISSUE TITLE
add support for lxc provider

### ISSUE THREAD

**Issue by gavinrogers** [pradels/vagrant-libvirt#159]
Would this be possible? Let me know what needs to be done and I would be able to help.

**Comment by infernix** [comment]
As I mentioned in #6:

> It would however be a significant amount of work and would require an expansion of the box metadata definition, since each hypervisor driver may need very different image formats, boot devices, bootloaders or even kernels. It's not clear to me whether if libvirt hypervisor driver subtypes can even be specified in the metadata for boxes of the same Vagrant provider.

> Additionally, there is the issue of fragmentation in available boxes; all existing boxes assume QEMU/KVM and they may not even work for different hypervisor driver, which would cause confusion for users. So adding this feature requires some serious thought as to not cause backwards compatibility issues with current and new boxes.

So it would be unlikely that  support for LXC can be added without breaking functionality; drivers for full machine emulation (Xen, Virtualbox) are much more compatible but even those are non-trivial. Lastly, given the fact that vagrant-lxc exists, I'm closing this in lieu of a PR from someone ready to work on these challenges.
