### ISSUE TITLE
Problem with ssh authentication 

### ISSUE THREAD

**Issue by maishsk** [pradels/vagrant-libvirt#160]
Host is RHEL 6.4
I have gone through all the steps - but cannot get this to work - I have the same error all the time.

[test_vm]  -- Command line :
 INFO machine: New machine ID: "8a7498e6-5fef-6768-900a-659119608774"
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::TimedProvision:0x007fd150ccf848>
 INFO provision: Checking provisioner sentinel if we should run...
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::CreateNetworks:0x007fd150d53eb8>
 INFO create_networks: Using vagrant-libvirt at 192.168.121.0/24 as the management network
 INFO create_networks: Saving information about created network vagrant-libvirt, UUID=ee0e4929-e399-1db7-e71e-9960388ca5a6 to file /root/vagrant/1/.vagrant/machines/test_vm/libvirt/created_networks.
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::CreateNetworkInterfaces:0x007fd150e203c8>
 INFO create_network_interfaces: Using vagrant-libvirt at 192.168.121.0/24 as the management network
 INFO create_network_interfaces: Creating network interface eth0 connected to network vagrant-libvirt.
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::StartDomain:0x007fd150ea1ab8>
 INFO interface: info: Starting domain.
[test_vm] Starting domain.
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::WaitTillUp:0x007fd150f25de0>
 INFO interface: info: Waiting for domain to get an IP address...
[test_vm] Waiting for domain to get an IP address...
ERROR warden: Error occurred: Error authenticating over ssh to host vbox72 and user root
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<VagrantPlugins::ProviderLibvirt::Action::WaitTillUp:0x007fd150f25de0>
 INFO machine: Calling action: read_state on provider Libvirt (8a7498e6-5fef-6768-900a-659119608774)

Strangely enough I get this as well when I try even without ssh.

Any ideas?

**Comment by pronix** [comment]
https://github.com/pradels/vagrant-libvirt/commit/0a23a986b36f3c552a653ec22912c1aa7e45afa5
