### ISSUE TITLE
Vagrant-libvirt should allow multiple config.vm.provider :libvirt blocks

### ISSUE THREAD

**Issue by purpleidea** [pradels/vagrant-libvirt#163]
I think vagrant-libvirt should allow multiple config.vm.provider :libvirt blocks. This would be useful if you want to use vagrant to build a cluster of machines where some of the VM's reside of libvirt host A, and some reside of libvirt host B, etc... Actually it would be great if this worked across different providers too!

Also, I'm being lame in that I haven't actually tested any of the above yet, because I don't have more than one host to try this on at the moment, but I'd like some feedback to know if you've tried this and it worked, or if you know it doesn't work, or if you know how to make it work (and can patch it if needed).

Cheers

**Comment by infernix** [comment]
Supporting multiple hosts within a single Vagrantfile  has been discussed before, but this needs to become a core Vagrant feature before vagrant-libvirt can fully support it.

Somewhat related but mostly for future reference, an example of a Vagrantfile that supports different providers for the same set of virtual machines could look like this:

```ruby
# Provider selection based on host OS
if RUBY_PLATFORM =~ /darwin/
        ENV['VAGRANT_DEFAULT_PROVIDER'] = 'parallels'
elsif RUBY_PLATFORM =~ /linux/
        ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
end

....

# Box selection based on host OS
      if RUBY_PLATFORM =~ /darwin/
        foo.vm.box = "parallels/debian-7.6"
      elsif RUBY_PLATFORM =~ /linux/
        foo.vm.box = "alxgrh/debian-jessie-x86_64"
      end

...

# Provider specific flags
foo.vm.provider :virtualbox do |v|
   ...
end
foo.vm.provider :libvirt do |v|
   ...
end
```

However this is for use on a single host.
