### ISSUE TITLE
dnsmasq should suppot relay(proxy mode) or require support dhcp in relay mode

### ISSUE THREAD

**Issue by pronix** [pradels/vagrant-libvirt#19]

**Comment by infernix** [comment]
I'm not sure what the reasoning is here, but I don't see any method of configuring this in libvirt explicitly. So if libvirt doesn't support this configuration I don't think vagrant-libvirt can.

If a Vagrant VM should receive an IP from an external DHCP server through a preexisting bridge, I think it'd be best to let that be handled with a private_network.

Can you describe the issue more clearly?

**Comment by pronix** [comment]
dnsmasq support relay mode, but, as you told, this feature can be get rounded much easy.

**Comment by infernix** [comment]
OK, closing this due to no apparent way to configure libvirt to set up dnsmasq for this, and the option of using private_network with pre-existing bridge interfaces.
