### ISSUE TITLE
Shared folders will fail when using remote libvirt host

### ISSUE THREAD

**Issue by sciurus** [pradels/vagrant-libvirt#222]
When using remote libvirt, we should disabled shared folders and warn the user they won't work.

Alternately, find a way to support tunneling them over ssh. This should be possible at least with rsync, although I don't know how easily we can add this since we use vagrant's implementation.

**Comment by erik-stephens** [comment]
I am able to sync folders of libvirt guests on a remote host, but I can only use rsync.  Instead of disabling, maybe just warn that only rsync synced folders are supported?

**Comment by pronix** [comment]
https://github.com/pradels/vagrant-libvirt/pull/373

**Comment by infernix** [comment]
Since rsync already worked and in #373 nfs was added, I'll close this for now, although I haven't tested remote 9p support.
