### ISSUE TITLE
Have a command to redo port forwarding (ssh tunnels)

### ISSUE THREAD

**Issue by obilodeau** [pradels/vagrant-libvirt#224]
It would be nice to have something like `vagrant forwarding reload` or something.

When connecting to libvirt via ssh on a remote machine the ssh tunnels created by vagrant-libvirt (the vagrant `forwarded_port` feature) often break and recreating them by hand is painful.

I know that `vagrant reload` recreates the tunnels but since it halts and restarts the VM it is less than ideal. For example I lose my various terminals running inside tmux tailing all the logs I need to look at.

I would be ready to look at the code and try to contribute it but wanted to know if there is interest and maybe what name should I give the new command?

**Comment by infernix** [comment]
I don't see any command in vagrant 1.8.1 to do this, and given the workaround mentioned above, I'm closing this. 

If upstream vagrant adds a command to do this, we can hook onto it, but as a plugin we are relying on upstream to provide such commands. I see no way of fixing this today.

**Comment by cunha** [comment]
In case you have multiple VMs and want to restart just the ones whose SSH forwarders have died:

```bash
#!/bin/bash
set -eu

if [[ ! -f "Vagrantfile" || ! -d .vagrant ]] ; then
    echo "run script in the directory where the Vagrantfile is located"
    exit 1
fi

declare -A vm2port=(
    ["cloud1"]="51978"
    ["cloud2"]="51979"
    ["cloud3"]="51981"
    ["cloud2b"]="51982"
)

for vm in "${!vm2port[@]}"; do
    port=${vm2port[$vm]}
    if pgrep -f "ssh.*\*:$port:" > /dev/null ; then
        echo "Port forwarding for $vm on port $port is already running"
        continue
    fi
    echo "Restarting port forwarding for $vm on port $port"
    vagrant ssh "$vm" -- -f -N -L "*:$port:localhost:22"
done
```
