### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by ri0t** [pradels/vagrant-libvirt#250]
Is there any way to set up arm kvms with vagrant-libvirt? Or: is this possible with vagrant at all?
I know that this involves a lot of non-standard stuff like preparing a boot loader etc..

**Comment by infernix** [comment]
Recent commits merged in Pr https://github.com/pradels/vagrant-libvirt/pull/581 allow for ARM support through CPU model selection and DTB choice. I'm closing this, if you have  problems using it please create new issues, thanks!
