### ISSUE TITLE
vagrant-libvirt and Windows guest, issues and questions

### ISSUE THREAD

**Issue by romu70** [pradels/vagrant-libvirt#251]
Hi,
I'm trying to deploy Windows boxes with vagrant-libvirt. First, I took an already existing W7 img file. This way, I can compare how both work and see issues.

I'm facing 3 problems for now:
- the hostname is not set
- the keyboard layout is just nothing valid. The Windows has 2 keyboards (EN and FR) and on both settings, lots of keys are all but correct
- "vagrant up" seems to be blocked on "==> w7: Waiting for SSH to become available..." and when I Ctrl+C, the VM is deleted.

What is strange is the same image is used for both my own reference VM and the vagrant box.

Any ideas? 

Here is my vagrant file

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "w7" 
  config.vm.define "w7" do |the|

    the.vm.box = "w7"
    the.vm.hostname = "w7"
    the.vm.guest = :windows
    
    the.vm.provider :libvirt do |libvirt|
        libvirt.driver = "kvm"
        libvirt.memory = 4096
        libvirt.connect_via_ssh = false
    end
  end
end
```

**Comment by pronix** [comment]
looks like windows guest supported https://github.com/pradels/vagrant-libvirt/pull/336
