### ISSUE TITLE
Rsync folders via ssh proxy if connected to remote hypervisor.

### ISSUE THREAD

**Issue by pradels** [pradels/vagrant-libvirt#26]
If controlling VMs on remote libvirt host, rsync to VM can fail if VM is not visible directly from our machine. This can be solved with ssh proxy. Remote libvirt host will act as proxy.

**Comment by infernix** [comment]
Closing due to supporting vagrants rsync and no comments on this for ~2 years; if this feature is still required please comment or open a new issue.
