### ISSUE TITLE
Authentication issue with a remote KVM server

### ISSUE THREAD

**Issue by romu70** [pradels/vagrant-libvirt#267]
Hi,
I'm trying to use vagrant-libvirt on a remote KVM server. As I don't want all users to upload their SSH keys to the server, I just want to work with login/password credentials.

First, I check I can access my KVM server by running:

```
virsh -c qemu+ssh://<user>@<server>/system nodeinfo
```

I'm asked for the <user> password and get the expected output.

Then, my next step is to "up" a box to the server. The "libvirt" part of the Vagrantfile is:

```
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "kvm"
    libvirt.storage_pool_name = "vms"
    libvirt.disk_bus = "ide"
    libvirt.video_type = "vga"
    libvirt.nic_model_type = "rtl8139"
    libvirt.memory = 1024
    # leave out host to connect directly with qemu:///system
    libvirt.host = "<server>"
    libvirt.username = "<user>"
    libvirt.password = "<password>"
    libvirt.connect_via_ssh = true
  end
```

When I "up" the box, I'm asked for the password, and I finally get an error within Fog:

```
/.vagrant.d/gems/gems/fog-1.23.0/lib/fog/libvirt/models/compute/server.rb:247:in `rescue in addresses': Error authenticating over ssh to host <server> and user <user> (Fog::Errors::Error)
```

As I've tried many times, I'm sure this is not a wrong password issue. Any idea about the problem?

**Comment by brandor5** [comment]
For what it's worth, we're seeing the same`issue`.

**Comment by icepic** [comment]
I see it too. And I don't really understand where it comes from, I am using ssh ControlMaster sockets so I can have an ssh open on the side and just ride on that connection for my virsh / libvirt things, but re-typing the pw over and over (in the clear!) seems really bad on so many levels.

**Comment by pronix** [comment]
https://github.com/pradels/vagrant-libvirt/commit/0a23a986b36f3c552a653ec22912c1aa7e45afa5

**Comment by evaryont** [comment]
I'm running into this issue again when I have password authentication turned off. (Leaving only public key authentication.) It seems as though Net::SSH isn't using my private key. My only thought is that it's an ed25519 key instead of RSA.
