### ISSUE TITLE
Problem with installing on ArchLinux

### ISSUE THREAD

**Issue by macseem** [pradels/vagrant-libvirt#268]
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ruby-libvirt (0.4.0), and Bundler cannot continue.
Make sure that `gem install ruby-libvirt -v '0.4.0'` succeeds before bundling.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby extconf.rb 
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/ruby
	--with-libvirt-include
	--without-libvirt-include
	--with-libvirt-lib
	--without-libvirt-lib
	--with-libvirt-config
	--without-libvirt-config
	--with-pkg-config
	--without-pkg-config
/opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:519:in `try_link0'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:534:in `try_link'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:620:in `block in try_ldflags'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:613:in `with_ldflags'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:619:in `try_ldflags'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:1725:in `pkg_config'
	from extconf.rb:82:in `<main>'

Gem files will remain installed in /root/.vagrant.d/gems/gems/ruby-libvirt-0.4.0 for inspection.
Results logged to /root/.vagrant.d/gems/gems/ruby-libvirt-0.4.0/ext/libvirt/gem_make.out

Only this helps:
CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib"

Add this to docs or make smth with it.

**Comment by bhundven** [comment]
For what it's worth, to install vagrant-libvirt on centos 7 x86_64, I had to do something similar:

```CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64" vagrant plugin install vagrant-libvirt```

**Comment by PierrickI3** [comment]
Thanks @bhundven, this fixed my issue on centos 7 x86_64 too!

**Comment by bhundven** [comment]
@PierrickI3 The problem I ran into next is #87 where I can't push an image to a remote storage domain.
I looked at the ruby-libvirt git: http://libvirt.org/git/?p=ruby-libvirt.git
where some of the changes look hopeful, but you can't build a development/non-tagged/non-released ruby gem in the vagrant-libvirt package. Maybe I'm wrong, but from what I grok, that is a limitation of bundler.

**Comment by infernix** [comment]
This isn't a bug or enhancement for vagrant-libvirt, although the build/install issues do warrant better documentation and perhaps some automated testing on the various distros and versions. I've made an issue on that as #590
