### ISSUE TITLE
9p shared folders can't be written from guest

### ISSUE THREAD

**Issue by dmick** [pradels/vagrant-libvirt#274]
On Ubuntu Trusty, libvirtd starts qemu procs as user libvirtd-qemu, group kvm.   vagrant-libvirt writes the libvirt XML with "accessmode=passthrough" (hardcoded), and that means that the uid/gid are passed through from the guest to the host when creating files; this leads to a permission error from qemu when attempting to write a shared file of type 9p, since vagrant/vagrant doesn't exist on the vmhost.

Workaround: use "accessmode=mapped" instead, which translates vagrant/vagrant to libvirtd-qemu/kvm.  I did this by hacking filesystem.xml.erb, but that's because I don't speak enough Ruby to easily figure out how to make it settable in the Vagrantfile through cap/synced_folder.rb's folder_opts.merge!() call.

**Comment by varac** [comment]
same here trying 9p for the first time.

```
vagrant@leap-wheezy:~$ mount | grep vagrant
/vagrant on /vagrant type 9p (rw,relatime,sync,dirsync,trans=virtio,version=9p2000.L)

vagrant@leap-wheezy:~$ touch /vagrant/test
touch: cannot touch `/vagrant/test': Permission denied

```

from the domain xml: 

```
…
    <filesystem type='mount' accessmode='passthrough'>
      <driver type='path' wrpolicy='immediate'/>
      <source dir='/home/varac/vagrant/vms/wheezy-tmp'/>
      <target dir='/vagrant'/>
      <alias name='fs0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </filesystem>
…
```

**Comment by varac** [comment]
btw, this is not too important for me, i'll just stick to nfs for now.

**Comment by flavio** [comment]
With latest version of vagrant-libvirt (0.0.24) it is possible to specify the access mode:

```ruby
config.vm.synced_folder ".", "/vagrant", type: "9p", accessmode: "mapped"
```

**Comment by varac** [comment]
it works, but not out of the box.
it i create a directory owned by myself, and fire up a vagrant vm in it, everthing works.
if i add a file on the host, i see it on th guest.

BUT when i try to modify this file (test-host), i get a permission denied:

```
vagrant@leap-wheezy:/vagrant$ echo test >> test-host 
-bash: test-host: Permission denied
```

if i try to create a file on the guest, also:

```
vagrant@leap-wheezy:/vagrant$ touch test-guest
touch: cannot touch `test-guest': Permission denied
```

if make the directory on the host world-writable (`chmod 777 .`), i can create a file from the guest (test-guest), but it has `libvirt-qemu` as owner:
```
--- vms/wheezy-tmp » ls -al
total 20
drwxrwxrwx 3 varac        varac 4096 Mar 20 16:57 .
drwxrwxr-x 7 varac        varac 4096 Feb  2 11:07 ..
-rw------- 1 libvirt-qemu kvm      0 Mar 20 16:57 test-guest
-rw-rw-r-- 1 varac        varac    0 Mar 20 16:56 test-host
drwxrwxr-x 3 varac        varac 4096 Feb  2 09:43 .vagrant
-rw-rw-r-- 1 varac        varac 3134 Mar 20 16:55 Vagrantfile
```

**Comment by varac** [comment]
is there a way to have the owner mapped to the user who runs vagrant ? this would be much more convinient

**Comment by pronix** [comment]
https://github.com/pradels/vagrant-libvirt/commit/4af0163c5eef4dd0a897d65601517136f768e3c9
for drop priv. in guest - use accessmode squash
and on mount step you can specify owner
should like 
```
config.vm.synced_folder './', '/vagrant', type: '9p', disabled: false, accessmode: "squash", owner: 'anyuser'
```
