### ISSUE TITLE
vagrant up fails on Debian Jessie with message: "unsupported configuration: SATA"

### ISSUE THREAD

**Issue by rafaelri** [pradels/vagrant-libvirt#279]
Recently I had moved back from Ubuntu to Debian (Jessie) and I am having trouble starting up my virtual machine with libvirt on vagrant. Strangely is the fact that I have a similar machine at work and it works there, the only difference is that the machine at work is AMD based whereas my personal is an Intel I7.
There is a bug filled against debian (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=756159) but they argued that using different options for creating the libvirt domain would resolve the problem.
For me it seems like vagrant libvirt is having issues creating the domain under certain circumstances.
Below is the whole error message:
rafaelri@samsung550p:~/Projetos/odk$ vagrant up db
Bringing machine 'db' up with 'libvirt' provider...
==> db: Starting domain.
There was an error talking to Libvirt. The error message is shown
below:

Call to virDomainCreateWithFlags failed: unsupported configuration: SATA is not supported with this QEMU binary

**Comment by pronix** [comment]
please update libvirt and qemu-kvm to latest stable versions. and show this versions
