### ISSUE TITLE
Install problems on Fedora 21

### ISSUE THREAD

**Issue by samon007** [pradels/vagrant-libvirt#290]
I tried to install vagrant-libvirt on a fresh Fedora 21 Installation.

```
➜  ~  vagrant version
Installed Version: 1.7.1
Latest Version: 1.7.1

You're running an up-to-date version of Vagrant!
```
I did a:

```
➜  ~  vagrant plugin install vagrant-libvirt 
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

An error occurred while installing ruby-libvirt (0.5.2), and Bundler cannot continue.
Make sure that `gem install ruby-libvirt -v '0.5.2'` succeeds before bundling.

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /opt/vagrant/embedded/bin/ruby extconf.rb 
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/opt/vagrant/embedded/bin/ruby
	--with-libvirt-include
	--without-libvirt-include
	--with-libvirt-lib
	--without-libvirt-lib
	--with-libvirt-config
	--without-libvirt-config
	--with-pkg-config
	--without-pkg-config
/opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:434:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:519:in `try_link0'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:534:in `try_link'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:620:in `block in try_ldflags'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:613:in `with_ldflags'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:619:in `try_ldflags'
	from /opt/vagrant/embedded/lib/ruby/2.0.0/mkmf.rb:1725:in `pkg_config'
	from extconf.rb:72:in `<main>'


Gem files will remain installed in /home/felix/.vagrant.d/gems/gems/ruby-libvirt-0.5.2 for inspection.
Results logged to /home/felix/.vagrant.d/gems/gems/ruby-libvirt-0.5.2/ext/libvirt/gem_make.out


```
And `mkfm.log`

```
➜  ~  cat /home/felix/.vagrant.d/gems/gems/ruby-libvirt-0.5.2/ext/libvirt/mkmf.log    
"gcc -o conftest -I/opt/vagrant/embedded/include/ruby-2.0.0/x86_64-linux -I/opt/vagrant/embedded/include/ruby-2.0.0/ruby/backward -I/opt/vagrant/embedded/include/ruby-2.0.0 -I.  -I/vagrant-substrate/staging/embedded/include   -I/vagrant-substrate/staging/embedded/include -fPIC conftest.c  -L. -L/opt/vagrant/embedded/lib -Wl,-R/opt/vagrant/embedded/lib -L/vagrant-substrate/staging/embedded/lib -Wl,-R/vagrant-substrate/staging/embedded/lib -lvirt     '-Wl,-rpath,/../lib' -Wl,-R -Wl,/opt/vagrant/embedded/lib -L/opt/vagrant/embedded/lib -lruby  -lpthread -lrt -ldl -lcrypt -lm   -lc"
/lib64/libsystemd.so.0: undefined reference to `lzma_stream_decoder@XZ_5.0'
/lib64/libxml2.so.2: undefined reference to `lzma_auto_decoder@XZ_5.0'
/lib64/libxml2.so.2: undefined reference to `lzma_properties_decode@XZ_5.0'
/lib64/libsystemd.so.0: undefined reference to `lzma_end@XZ_5.0'
/lib64/libsystemd.so.0: undefined reference to `lzma_code@XZ_5.0'
collect2: error: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

I also installed the know dependencies: `libxslt-devel`, `libxml2-devel` and `libvirt-devel`

**Comment by sciurus** [comment]
What if you run `yum-builddep ruby-libvirt` first?

**Comment by samon007** [comment]
There was already everything installed and the  `vagrant plugin install vagrant-libvirt` still fails.

```
➜  ~  sudo yum-builddep  ruby-libvirt                                    
Loaded plugins: langpacks
Enabling fedora-source repository
Enabling rpmfusion-free-source repository
Enabling rpmfusion-free-updates-source repository
Enabling rpmfusion-nonfree-source repository
Enabling rpmfusion-nonfree-updates-source repository
Enabling updates-source repository
http://linux.dropbox.com/fedora/21/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
rpmfusion-free-source                                                                                                                                                        | 2.7 kB  00:00:00     
rpmfusion-free-updates-source                                                                                                                                                | 2.7 kB  00:00:00     
rpmfusion-nonfree-source                                                                                                                                                     | 2.7 kB  00:00:00     
rpmfusion-nonfree-updates-source                                                                                                                                             | 2.7 kB  00:00:00     
updates-source/21/x86_64/metalink                                                                                                                                            |  24 kB  00:00:00     
updates-source                                                                                                                                                               | 3.7 kB  00:00:00     
updates-source/21/x86_64/primary_db                                                                                                                                          | 554 kB  00:00:00     
(1/6): rpmfusion-nonfree-updates-source/21/x86_64/primary_db                                                                                                                 | 7.6 kB  00:00:00     
(2/6): rpmfusion-free-updates-source/21/x86_64/primary_db                                                                                                                    |  13 kB  00:00:00     
(3/6): rpmfusion-nonfree-source/21/x86_64/primary_db                                                                                                                         |  36 kB  00:00:00     
(4/6): updates-source/21/x86_64/updateinfo                                                                                                                                   | 336 kB  00:00:00     
(5/6): rpmfusion-free-source/21/x86_64/primary_db                                                                                                                            |  92 kB  00:00:00     
(6/6): updates-source/21/x86_64/pkgtags                                                                                                                                      | 1.3 MB  00:00:01     
fedora-source/21/x86_64/primary_db      
Getting requirements for ruby-libvirt-0.5.2-5.fc21.src
 --> Already installed : rubygem-rdoc-4.1.1-2.fc21.noarch
 --> Already installed : rubygem-rake-10.1.0-25.fc21.noarch
 --> Already installed : ruby-devel-2.1.5-25.fc21.x86_64
 --> Already installed : ruby-2.1.5-25.fc21.x86_64
 --> Already installed : libvirt-devel-1.2.9.1-2.fc21.x86_64
Getting requirements for ruby-libvirt-0.5.2-5.fc21.src
 --> Already installed : rubygem-rdoc-4.1.1-2.fc21.noarch
 --> Already installed : rubygem-rake-10.1.0-25.fc21.noarch
 --> Already installed : ruby-devel-2.1.5-25.fc21.x86_64
 --> Already installed : ruby-2.1.5-25.fc21.x86_64
 --> Already installed : libvirt-devel-1.2.9.1-2.fc21.x86_64
```

**Comment by sciurus** [comment]
Okay; I'll try to take a look.

**Comment by bariscicek** [comment]
I had the same problem and issue is because of mismach of liblzma libraries in vagrant installation. 

If /usr/lib64/liblzma.so.5 is copied to /opt/vagrant/embedded/lib (which replaces distributed file with vagrant rpm) directory plugin compiles without any problem. But this might cause other mismatches elsewhere.

This might be a vagrant distribution issue than a plugin issue.

**Comment by samon007** [comment]
I can confirm that @bariscicek solution works.
I exchanged all `liblzma.so*` for the ones from `/usr/lib64/`. After that the plugin installs just fine.

Installing `vagrant-kvm` before leads to the same error. Afterwards it also installs just fine.

**Comment by sciurus** [comment]
Hmm, sounds like vagrant may need to ship a newer version if liblzma. Have you checked if there is an open issue on https://github.com/mitchellh/vagrant ?

**Comment by samon007** [comment]
I couldn't find one

**Comment by samon007** [comment]
It may be similar to: https://github.com/mitchellh/vagrant/issues/3893 since lzma is broken.

**Comment by samon007** [comment]
I wrote a new summary and opened a issue on https://github.com/mitchellh/vagrant

**Comment by obnoxxx** [comment]
I have worked on getting vagrant with libvirt (and lxc) running on fedora21.
Problem is that the installed liblzma has symbol versions and the libs like
libxml2 depend on these versions. Now the linker search paths in the
plugin install run are changed, the vagrant liblzma is used, and this has
no symbol versions....

There is a trick I found to work: use the gold linker instead of the bfd one:

alternatives --set ld /usr/bin/ld.gold

Here is the long story:

http://blog.obnox.de/vagrant-with-lxc-and-libvirt-on-fedora

**Comment by sciurus** [comment]
Great investigation @obnoxxx !

Does something like `export CFLAGS='-fuse-ld=gold'` work instead of changing the linker via `alternatives`?

**Comment by bhundven** [comment]
as I mentioned in #268 : 

```CONFIGURE_ARGS="with-libvirt-include=/usr/include/libvirt with-libvirt-lib=/usr/lib64" vagrant plugin install vagrant-libvirt```

worked for me on centos7. Maybe helpful on f21?

**Comment by sciurus** [comment]
I _think_ those are two separate issues  @bhundven , but thanks for posting it here for anyone to try.

**Comment by maxfrigge** [comment]
Had the same issue when trying to install on Fedora 21. For me using bhundven's solution worked.

**Comment by pronix** [comment]
@maxfrigge for fedora 21 it is distributed by rpm

**Comment by maxfrigge** [comment]
@pronix thanks! Did not know that. A hint in the readme would be nice :)

**Comment by pronix** [comment]
@maxfrigge your are welcome PR :)

**Comment by maxfrigge** [comment]
Just  uninstalled the plugin and installed again with yum. I get a warning during install and cannot use the libvirt provider after that (The provider 'libvirt' could not be found..). Guess it's best to just stick to the workaround provided by @bhundven

Here's the output

    Total                                                                                                                                                                                                                    2.4 MB/s | 2.1 MB  00:00:00     
    Running transaction check
    Running transaction test
    Transaction test succeeded
    Running transaction (shutdown inhibited)
      Installing : rubygem-nokogiri-1.6.6.2-1.fc21.x86_64                                                                                                                                                                                               1/15 
      Installing : rubygem-net-ssh-2.9.1-1.fc21.noarch                                                                                                                                                                                                  2/15 
      Installing : rubygem-multi_json-1.8.4-2.fc21.noarch                                                                                                                                                                                               3/15 
      Installing : rubygem-fog-json-1.0.0-1.fc21.noarch                                                                                                                                                                                                 4/15 
      Installing : rubygem-net-scp-1.2.1-1.fc21.noarch                                                                                                                                                                                                  5/15 
      Installing : rubygem-ipaddress-0.8.0-8.fc21.noarch                                                                                                                                                                                                6/15 
      Installing : rubygem-excon-0.33.0-2.fc21.noarch                                                                                                                                                                                                   7/15 
      Installing : rubygem-formatador-0.2.4-6.fc21.noarch                                                                                                                                                                                               8/15 
      Installing : rubygem-ruby-libvirt-0.4.0-8.fc21.x86_64                                                                                                                                                                                             9/15 
      Installing : rubygem-mime-types-1.25.1-1.fc21.noarch                                                                                                                                                                                             10/15 
      Installing : rubygem-builder-3.2.2-2.fc21.noarch                                                                                                                                                                                                 11/15 
      Installing : rubygem-fog-core-1.22.0-2.fc21.noarch                                                                                                                                                                                               12/15 
      Installing : rubygem-fog-brightbox-0.0.2-1.fc21.noarch                                                                                                                                                                                           13/15 
      Installing : rubygem-fog-1.22.1-1.fc21.noarch                                                                                                                                                                                                    14/15 
      Installing : vagrant-libvirt-0.0.24-3.fc21.noarch                                                                                                                                                                                                15/15 
    /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- vagrant/plugin/manager (LoadError)
    	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
    	from -e:3:in `<main>'
    warning: %posttrans(vagrant-libvirt-0.0.24-3.fc21.noarch) scriptlet failed, exit status 1
    Non-fatal POSTTRANS scriptlet failure in rpm package vagrant-libvirt-0.0.24-3.fc21.noarch
      Verifying  : rubygem-builder-3.2.2-2.fc21.noarch                                                                                                                                                                                                  1/15 
      Verifying  : rubygem-fog-json-1.0.0-1.fc21.noarch                                                                                                                                                                                                 2/15 
      Verifying  : rubygem-mime-types-1.25.1-1.fc21.noarch                                                                                                                                                                                              3/15 
      Verifying  : rubygem-ruby-libvirt-0.4.0-8.fc21.x86_64                                                                                                                                                                                             4/15 
      Verifying  : rubygem-fog-core-1.22.0-2.fc21.noarch                                                                                                                                                                                                5/15 
      Verifying  : rubygem-formatador-0.2.4-6.fc21.noarch                                                                                                                                                                                               6/15 
      Verifying  : rubygem-multi_json-1.8.4-2.fc21.noarch                                                                                                                                                                                               7/15 
      Verifying  : rubygem-net-scp-1.2.1-1.fc21.noarch                                                                                                                                                                                                  8/15 
      Verifying  : rubygem-net-ssh-2.9.1-1.fc21.noarch                                                                                                                                                                                                  9/15 
      Verifying  : rubygem-fog-brightbox-0.0.2-1.fc21.noarch                                                                                                                                                                                           10/15 
      Verifying  : vagrant-libvirt-0.0.24-3.fc21.noarch                                                                                                                                                                                                11/15 
      Verifying  : rubygem-nokogiri-1.6.6.2-1.fc21.x86_64                                                                                                                                                                                              12/15 
      Verifying  : rubygem-excon-0.33.0-2.fc21.noarch                                                                                                                                                                                                  13/15 
      Verifying  : rubygem-ipaddress-0.8.0-8.fc21.noarch                                                                                                                                                                                               14/15 
      Verifying  : rubygem-fog-1.22.1-1.fc21.noarch                                                                                                                                                                                                    15/15 

    Installed:
      vagrant-libvirt.noarch 0:0.0.24-3.fc21                                                                                                                                                                                                                 

    Dependency Installed:
      rubygem-builder.noarch 0:3.2.2-2.fc21          rubygem-excon.noarch 0:0.33.0-2.fc21             rubygem-fog.noarch 0:1.22.1-1.fc21               rubygem-fog-brightbox.noarch 0:0.0.2-1.fc21         rubygem-fog-core.noarch 0:1.22.0-2.fc21         
      rubygem-fog-json.noarch 0:1.0.0-1.fc21         rubygem-formatador.noarch 0:0.2.4-6.fc21         rubygem-ipaddress.noarch 0:0.8.0-8.fc21          rubygem-mime-types.noarch 0:1.25.1-1.fc21           rubygem-multi_json.noarch 0:1.8.4-2.fc21        
      rubygem-net-scp.noarch 0:1.2.1-1.fc21          rubygem-net-ssh.noarch 0:2.9.1-1.fc21            rubygem-nokogiri.x86_64 0:1.6.6.2-1.fc21         rubygem-ruby-libvirt.x86_64 0:0.4.0-8.fc21         

    Complete!

**Comment by obnoxxx** [comment]
@maxfrigge : did you also install vagrant itself from system rpms? You need to uninstall your vagrant and do "yum install vagrant vagrant-libvirt" - mixing won't work.

**Comment by maxfrigge** [comment]
@obnoxxx You are right... I was mixing :) It's working now.

**Comment by pronix** [comment]
so rpm or https://github.com/pradels/vagrant-libvirt/commit/311bdc5f23e6d8d2f4f10236fa094b7960b2fe9d

**Comment by Momus** [comment]
Not sure if it is the same issue, but it is still very frustrating.  I've followed @obnoxxx  excellent guide to install libvirt.  Then I had other Vagrant problems, decided to reinstall all and start fresh.  Reinstall Vagrant from rpm on Vagrant's website, then try to install plugin; it fails because of Nokogiri dependencies.  After hour of fiddling with gems, I start over again, but install another plugin (mutate) first.  After that, libvirt installs with no problem.
I realize my situation is atypical: I'm on Fedora 21, not 22, and I don't want to use the Fedora libvirt package because it pulls in sooo many ruby dependencies, and I am afraid it will cause conflicts with my rvm rubies that are in constant use. (Maybe I'm just paranoid)
However, just in case it is useful, here is a paste of my troubles:
http://pastebin.com/vahjHFUV
