### ISSUE TITLE
Feature Request: CIFS support

### ISSUE THREAD

**Issue by odigity** [pradels/vagrant-libvirt#297]
I rely on bi-directional shared folders, but I hate NFS.  Would be nice to support CIFS/SMB.

It looks like Vagrant is now able to support SMB through plugins, but by default only supports Windows hosts:

https://docs.vagrantup.com/v2/synced-folders/smb.html

    "Windows only! SMB is currently only supported when the host machine is Windows."

So perhaps it's not worth adding to vagrant-libvirt yet.  Still, wanted to have the request filed for future reference.

**Comment by sciurus** [comment]
Support for syncing via SMB on a linux host machine is definitely something that would be developed in vagrant, then enabled in vagrant-libvirt. Do you have an issue open with vagrant that we could track here?

**Comment by odigity** [comment]
I don't know if this is *the* issue, but it's *an* issue (related, anyway):

https://github.com/mitchellh/vagrant/issues/1749

**Comment by sciurus** [comment]
Hi @odigity I hope you don't mind if I close this for now. Let's reopen it if/when vagrant adds support.
