### ISSUE TITLE
Issues with handling ED25519 keys

### ISSUE THREAD

**Issue by zer0def** [pradels/vagrant-libvirt#299]
This is what I get immediately when WaitTillUp is called, while passing a ed25519 key to it.

```
INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::WaitTillUp:0x000000039a7e48>
INFO interface: info: Waiting for domain to get an IP address...
INFO interface: info: ==> centos66_64: Waiting for domain to get an IP address...
==> centos66_64: Waiting for domain to get an IP address...
ERROR warden: Error occurred: Error authenticating over ssh to host <host> and user <user>
```

From here, it starts recovery and tearing down the machine.

**Comment by sciurus** [comment]
Can you post your Vagrantfile?

**Comment by zer0def** [comment]
```
# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'yaml'

ENV['DEFAULT_VAGRANT_PROVIDER'] = 'libvirt'
myhv = YAML.load_file 'priviet.yml'

Vagrant.configure(2) do |config|
  config.vm.provider :libvirt do |daemon|
    daemon.host = myhv['host']
    daemon.username = myhv['username']
    daemon.connect_via_ssh = myhv['ssh_connect']
    daemon.id_ssh_key_file = myhv['key']
    daemon.nested = true
    daemon.random_hostname = true
  end

  config.vm.network :private_network, :libvirt__network_name => "default"
  config.ssh.pty = true
  config.ssh.password = "vagrant"

  config.vm.define "centos66_64" do |centos66_64|
    centos66_64.vm.box = "centos6.6_64"
    centos66_64.vm.provider :libvirt do |domain|
      # domain.cpus = 1  # defaults to 1
      # domain.memory = 1024  # in megabytes, defaults to 512
    end
  end
end
```

When myhv['key'] points to a ed25519 key, it immediately throws an error (possibly a SSH-handling lib bug?).

**Comment by sciurus** [comment]
Is this bug unique to vagrant-libvirt, or does it also occur if you use vagrant's virtualbox provider?

**Comment by zer0def** [comment]
I'm sorry, but how would it relate to a virtualbox provider, when it explicitly misbehaves on an option that's available only in vagrant-libvirt, when it's connecting to a remote host?

**Comment by sciurus** [comment]
Sorry, I responded too quickly. Yes, I see now that the problematic key is in the provider config, not the vm config.

**Comment by zer0def** [comment]
Yeah, sorry for being rudely explicit. RSA keys work, though, but RSA's days are numbered.

**Comment by zer0def** [comment]
So a friendly Ruby dev did quick digging and apparently the issue lies within net-ssh not supporting Curve25519 after all this time. Sad day for you guys, closing the ticket.
