### ISSUE TITLE
Multimachine boot sequence

### ISSUE THREAD

**Issue by billxinli** [pradels/vagrant-libvirt#301]
Hi:

Vagrant allows for Vagrantfile to define multiple VMs, and during the `vagrant up` process, the VMs are booted from top to bottom, sequentially. During the `vagrant halt`, the opposite order.

I am noticing that with `vagrant-libvirt` it boots all the VMs in parallel. 

tl;dr: Is there a way to allow the VMs boot sequentially?

**Comment by nspaeth** [comment]
Vagrant boots multimachine VMs in parallel by default, so this shouldn't be specific to vagrant-libvirt.
Have you already tried the `--no-parallel` option?

**Comment by billxinli** [comment]
Cheers. `--no-parallel` solved the problem.

I must have been using an older version of Vagrant, or virtualbox doesn't support parallel booting...
