### ISSUE TITLE
Is Vagrant 1.7 supported?

### ISSUE THREAD

**Issue by facastagnini** [pradels/vagrant-libvirt#302]
As of today, the last version of Vagrant is 1.7.2, and according to the README the plugin is supported only over Vagrant 1.5 and 1.6.

Is this a real constrain or is the README outdated?
Anyone using this plugin with Vagrant 1.7?

Thanks

**Comment by tkrille** [comment]
I'm running vagrant-libvirt with Vagrant 1.7.2 on multiple Debian Wheezy machines. So far I did not encounter any issues, hth.

**Comment by sciurus** [comment]
Thanks for the report @tkrille !
