### ISSUE TITLE
Cannot determine IP on libvirt v1.2.11 with leaseshelper and RO lease file

### ISSUE THREAD

**Issue by domcleal** [pradels/vagrant-libvirt#307]
libvirt v1.2.6 started using dnsmasq's --dhcp-script option, which calls a libvirt binary to notify it about lease changes.  Since libvirt v1.2.11 though, it adds --leasefile-ro which stops it updating the dnsmasq lease file (which vagrant-libvirt queries) and makes libvirt store the leases itself, so vagrant-libvirt can no longer find the IP address allocated to the new VM as the old lease file's not updated.

http://libvirt.org/git/?p=libvirt.git;a=commit;h=baafe668fa56767c031468ccd5df3e62eaa11370 (adding leasehelper)
http://libvirt.org/git/?p=libvirt.git;a=commit;h=0f87054b61d73493fb505ecb97bd16615bc53699 (adds leasefile-ro)

leasehelper seems to write a JSON status file, but it's named after the bridge name, not the network name...

<pre>
$ sudo cat /var/lib/libvirt/dnsmasq/virbr0.status
[
    {
        "ip-address": "192.168.122.133",
        "mac-address": "52:54:00:83:69:b7",
        "hostname": "ubuntu",
        "expiry-time": 1424258362
    }
]
</pre>

But this looks fairly private to me, I don't know if it's considered stable.

It looks like the best option is to call leaseshelper with the "init" argument which is a required behaviour when using leasefile-ro, and it outputs the leases in the usual dnsmasq format:

<pre>
$ sudo VIR_BRIDGE_NAME=virbr0 /usr/libexec/libvirt_leaseshelper init                                          
1424258362 52:54:00:83:69:b7 192.168.122.133 ubuntu *
</pre>

Again, you need to specify the bridge, not network name.  This option is only supported since the leasefile-ro change in v1.6.11 though, versions between .6 and .11 will use this helper binary, but won't support "init".

Observed on libvirt 1.2.12 on Fedora 21 with the preview repository: https://fedoraproject.org/wiki/Virtualization_Preview_Repository:

<pre>
Bringing machine 'default' up with 'libvirt' provider...
==> default: Creating image (snapshot of base box volume).
==> default: Creating domain with the following settings...
==> default:  -- Name:          foremandeb_1424256039_7de5f8d6be5a0ace3a86
==> default:  -- Domain type:   kvm
==> default:  -- Cpus:          1
==> default:  -- Memory:        1024M
==> default:  -- Base box:      fm-ubuntu1404
==> default:  -- Storage pool:  default
==> default:  -- Image:         /home/libvirt/foremandeb_1424256039_7de5f8d6be5a0ace3a86.img
==> default:  -- Volume Cache:  default
==> default:  -- Kernel:        
==> default:  -- Initrd:        
==> default:  -- Command line : 
==> default: Starting domain.
==> default: Waiting for domain to get an IP address...
==> default: Removing domain...
/home/dcleal/.vagrant.d/gems/gems/fog-core-1.28.0/lib/fog/core/wait_for.rb:11:in `wait_for': The specified wait_for timeout (2 seconds) was exceeded (Fog::Errors::TimeoutError)
</pre>

**Comment by domcleal** [comment]
Gah, apologies for the noise.  I see it's been fixed in master: 267de056bf6b9289b64c6ed6979619790366befe

**Comment by sciurus** [comment]
Thanks for the report and verification of the fix!
