### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by facastagnini** [pradels/vagrant-libvirt#311]
I see little activity, is this still an active project?
This is a very useful plugin, and I am concerned that maybe people moved somewhere else and I didn't find out.

**Comment by pronix** [comment]
alive

**Comment by facastagnini** [comment]
@pronix I know you  guys must be really busy, but there is a few PR queued that will be nice to have merged, at least the ones improving the documentation (#304 #305 #308 #309).

If you or @sciurus can take a look at them it will be nice.

I really appreciate that you are sharing all this hard work!
Thank you!

**Comment by sciurus** [comment]
Hi @facastagnini , I started a new job recently; this has caused me to neglect vagrant-libvirt.

It is my intention to continue reviewing PRs and troubleshooting issues.

**Comment by facastagnini** [comment]
We all have busy live, believe me, I totally understand. 

The thing is that I am working on a new project and I am using a lot of new tools, Every time I spend a couple hours working on some bug or incompatibility I try to submit a PR to share the code fix or improve the documentation, but sadly I submitted PR to several projects just to find that they where semi-abandoned.

For example I begin trying to implement vagrant-kvm, and just when I was realizing that the project was really outdated I found a message from the owner's thoughts about retiring the plugin in favor of vagrant-libvirt. (https://github.com/adrahon/vagrant-kvm/issues/276)

Therefore I started contributing here, since it is now more important to keep this project alive.

I am here to help, let me know if you need a hand with anything.
