### ISSUE TITLE
Sync vagrant folder on action 'provision'

### ISSUE THREAD

**Issue by vills** [pradels/vagrant-libvirt#315]
Vagrant-libvirt sync vagrant's folder only on VM creation. Thought it should sync folders also on provision.

**Comment by sciurus** [comment]
I think the current behavior is correct. When using rsync, [vagrant](http://docs.vagrantup.com/v2/synced-folders/rsync.html) only syncs folders on `vagrant up` or `vagrant reload`.

If you try an rsync shared folder with virtualbox and it behaves differently, please reopen this.
