### ISSUE TITLE
Call to virDomainCreateWithFlags failed: Invalid argument

### ISSUE THREAD

**Issue by mconigliaro** [pradels/vagrant-libvirt#316]
Anyone seen this one before?

```
STDERR: There was an error talking to Libvirt. The error message is shown
below:

Call to virDomainCreateWithFlags failed: Invalid argument
```

That error message is totally useless, so I'm still trying to figure out what argument it's talking about. FWIW, this is on CentOS 7.

**Comment by mconigliaro** [comment]
I get the same error using virsh directly, so I'm guessing it's something in `/etc/libvirt/qemu/*.xml`...

```
virsh start foo
error: Failed to start domain foo
error: Invalid argument
```

**Comment by mconigliaro** [comment]
The problem is that my resulting VM name is too long: https://bugzilla.redhat.com/show_bug.cgi?id=1033369

Maybe the `random_hostname` option can be fixed to reduce the size? This seems *very* random:

```
domain_name << "_#{Time.now.utc.to_i}_#{SecureRandom.hex(10)}" if config.random_hostname
```

That call to `SecureRandom.hex` results in 16^10 combinations. Are we really worried we're going to generate that many VMs in a second? I would think `Time.now.utc.to_f` (with the milliseconds) is enough. I'm also getting `default_` appended to my VM name somehow.

**Comment by mconigliaro** [comment]
Here's what's working for me for now. It basically mirrors what Vagrant does with the VirtualBox driver:

```ruby
domain_name << "_#{Time.now.utc.to_f.to_s.gsub('.', '_')}" if config.random_hostname
```

**Comment by sciurus** [comment]
@mconigliaro can you read through #215 and let me know what you think?

**Comment by mconigliaro** [comment]
@sciurus I left a comment on #215.

**Comment by tya** [comment]
@mconigliaro I'm now fighting this old problem of yours...any ideas on how to continue?

**Comment by mconigliaro** [comment]
Hey @tya, I'm assuming this broke after you updated the gems? Last time this bit me, I believe I just edited the installed gem with that last snippet I pasted above (try searching for `SecureRandom.hex`). Not a great solution since it'll break again every time someone updates the gem, but it got me going. Someone should probably submit an update to @nicot's patch to fix this permanently.

**Comment by tya** [comment]
@mconigliaro thanks for the tip Mike

**Comment by infernix** [comment]
Closing this because of #216 as well as #545 where we will need to address the name length regardless of user-specified or random.
