### ISSUE TITLE
Improve error message when box.img is missing

### ISSUE THREAD

**Issue by Shumakriss** [pradels/vagrant-libvirt#320]
Apologies for not knowing markdown formatting yet! 

I follwed the box file format: http://docs.vagrantup.com/v2/boxes/format.html

If using a path other than box.img in the local directory when tarring the box, vagrant-libvirt will throw an error trying to find the box. This stack trace tells me we are looking for something named box.img in the top directory but perhaps we should look recursively for an img or qcow2 file:

[shumakriss@localhost ~/vagrantfiles ]$ vagrant up
Bringing machine 'default' up with 'libvirt' provider...
==> default: Uploading base box image as volume into libvirt storage...
/usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/handle_box_image.rb:46:in `size': No such file or directory @ rb_file_s_size - /home/shumakriss/.vagrant.d/boxes/testbox64/0/libvirt/box.img (Errno::ENOENT)
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/handle_box_image.rb:46:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/handle_storage_pool.rb:21:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/gems/gems/vagrant-libvirt-0.0.24/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
	from /usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
	from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
	from /usr/share/vagrant/lib/vagrant/machine.rb:214:in `action_raw'
	from /usr/share/vagrant/lib/vagrant/machine.rb:191:in `block in action'
	from /usr/share/vagrant/lib/vagrant/environment.rb:516:in `lock'
	from /usr/share/vagrant/lib/vagrant/machine.rb:178:in `call'
	from /usr/share/vagrant/lib/vagrant/machine.rb:178:in `action'
	from /usr/share/vagrant/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by sciurus** [comment]
Why can't you just name it box.img?

Like the vagrant documentation says, the box file "is specific to a single provider and can contain anything." In vagrant-libvirt's README we document our box file requirements:

> Box Format
>
>You can view an example box in the example_box/directory. That directory also contains instructions on how to build a box.
>
>The box is a tarball containing:
>
>    qcow2 image file named box.img.
>    metadata.json file describing box image (provider, virtual_size, format).
>    Vagrantfile that does default settings for the provider-specific configuration for this provider.

**Comment by Shumakriss** [comment]
Sorry, I may have missed that in my haste to use vagrant-libvirt! In either case, perhaps we could handle the error better be catching the "No such file" and rethrowing an error like "Vagrant-libvirt requires a file named box.img but none was found".

**Comment by sciurus** [comment]
No worries, an explicit check for the disk image and an improved error message is a good idea.
