### ISSUE TITLE
Allow for isolated (guest-only) networks

### ISSUE THREAD

**Issue by mperedim** [pradels/vagrant-libvirt#324]
I have a Vagrantfile that looks similar to the following: 

...
  internal0 = <unique name; calculated by Vagrant workspace dir and uid>
  config.vm.define "dummybox" do |dummybox|
    dummybox.vm.hostname = "dummybox"
    dummybox.vm.network "private_network",
      ip: "192.168.99.3",
      libvirt__network_name: "#{internal0}",
      libvirt__netmask: "255.255.255.0",
      libvirt__dhcp_enabled: false,
      libvirt__forward_mode: "none"
  end
...

The intent is to share this environment among many users in the same system. Unfortunately this is not possible since libvirt doesn't seem to allow for multiple libvirt networks with "<ip address='192.168.99.1' netmask='255.255.255.0'></ip>". The problem is easy to reproduce by creating two files: 

testnet1.xml: 
<network connections='1' ipv6='yes'>
  <name>foo-0-internal1</name>
  <bridge name='virbr11' stp='on' delay='0' />
  <ip address='192.168.110.1' netmask='255.255.255.0'>
  </ip>
</network>
testnet2.xml
<network connections='1' ipv6='yes'>
  <name>foo-0-internal2</name>
  <bridge name='virbr12' stp='on' delay='0' />
  <ip address='192.168.110.1' netmask='255.255.255.0'>
  </ip>
</network>

and doing "net-define" then "net-start"; the second network will fail. 

libvirt introduces the concept of isolated networks where the <ip> field maybe omitted [cf. https://libvirt.org/formatnetwork.html#examplesNoGateway]. Supporting this on vagrant-libvirt seems to be fairly easy: 
1- introduce another forward mode, called "isolated" or "guestonly"
2- skip the "<ip>...</ip>" declaration for said forward mode

https://github.com/pradels/vagrant-libvirt/compare/master...mperedim:master provides a diff that does the tric. Would appreciate it if this gets merged in the next version.

**Comment by Brandl** [comment]
If you have a working solution, why not provide it as a pull request?

**Comment by Brandl** [comment]
If you have a working solution, why not provide it as a pull request?

**Comment by pronix** [comment]
@Brandl  :+1:
