### ISSUE TITLE
Adding PCI passthrough 

### ISSUE THREAD

**Issue by brecode** [pradels/vagrant-libvirt#325]
I was wondering if there is something like that in place: 
```xml
<hostdev mode='subsystem' type='pci' managed='yes'>
  <source>
    <address domain='0x0000' bus='0x07' slot='0x10' function='0x3'/>
  </source>
   …
</hostdev>
```
If not what are the files I should change to add this functionality ?
Thanks

**Comment by pronix** [comment]
https://github.com/pradels/vagrant-libvirt/issues/326

**Comment by petRUShka** [comment]
Same request. I'm waiting for such functionality. 

Link to corresponding libvirt help page: http://libvirt.org/guide/html/Application_Development_Guide-Device_Config-PCI_Pass.html

**Comment by pronix** [comment]
"waiting" the best strategy in opensource :)

**Comment by petRUShka** [comment]
@pronix :) Sometimes that strategy just works :) By the way, is it true that `hostdev` block should be placed inside `domain` block on first level?

**Comment by infernix** [comment]
Closing since this was merged
