### ISSUE TITLE
public_network documentation is wrong. Need to add 'type' parameter doc and correct example

### ISSUE THREAD

**Issue by jcsalem** [pradels/vagrant-libvirt#330]
README.md gives this an example of how to configure a guest network device that's bridged to the hosts public network =>
  `test_vm1.vm.network :public_network, :dev => "eth0", :mode => 'bridge'`
To get that to work on my kvm server running Ubuntu 14.04 I had to rename the `:mode` parameter to `:type` and use `br0` as the name of the network device =>
  `test_vm1.vm.network :public_network, :dev => "br0", :type => 'bridge'`

Unfortunately, `:type` isn't even defined in README.md.  I found it via the code: vagrant-libvirt/lib/vagrant-libvirt/templates/public_interface.xml.erb

I recommend updating README.md:
 1) Replace the example as shown above.  Note in the description that one may need to create `br0` on the host if it doesn't exist: E.G., `virsh iface-bridge eth0 br0`
 2) Add a definition of the `:type` parameter in the **Public Network Options** section. 
I'm happy to make a PR for these changes if you'd like.

### More Detail from virsh dumpxml on the libvirt/kvm vm
  `test_vm1.vm.network :public_network, :dev => "eth0", :mode => 'bridge'`
produces the non-working
```
     <interface type='direct'>
      <mac address='52:54:00:5b:89:d9'/>
      <source dev='eth0' mode='bridge'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </interface>
```
while
  `test_vm1.vm.network :public_network, :dev => "br0", :type => 'bridge'```
produces the working
```
   <interface type='bridge'>
      <mac address='52:54:00:65:35:ef'/>
      <source bridge='br0'/>
      <target dev='vnet1'/>
      <model type='virtio'/>
      <alias name='net1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </interface>
```

**Comment by pronix** [comment]
thanks @jcsalem
