### ISSUE TITLE
Can't get remote vagrant to work

### ISSUE THREAD

**Issue by jcsalem** [pradels/vagrant-libvirt#331]
I'd like to take advantage of the ssh feature of vagrant-libvirt.  However, vagrant is unable to find the remote box. The exact same Vagrantfile works fine on the machine running libvirtd whether or not I'm using connect_via_ssh. However, that Vagrant file doesn't work remotely.

This is the error I'm getting:

```
==> jsalem: Box 'trusty64' could not be found. Attempting to find and install...
    jsalem: Box Provider: libvirt
    jsalem: Box Version: >= 0
==> jsalem: Adding box 'trusty64' (v0) for provider: libvirt
    jsalem: Downloading: trusty64
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /home/jsalem/vagtest/trusty64
```

And here is the Vagrantfile
```
# -*- mode: ruby -*-

# Vagrantfile API/syntax version. 
VAGRANTFILE_API_VERSION = "2"

# Make libvirt (kvm) the default provider
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Provider host configuration
  config.vm.provider :libvirt do |libvirt|
    libvirt.storage_pool_name = 'VagrantVMs'
    libvirt.host = 'bos-kvm02'
    libvirt.username = 'jsalem'
    libvirt.connect_via_ssh = true
  end

  # Define the machines controlled by this Vagrantfile
  config.vm.define "jsalem" do |machine|
    machine.vm.box = 'trusty64'
    machine.vm.network :public_network, ip: '10.150.60.201', dev: 'br0', type: 'bridge'
  end

end
```

Details:
vagrant 1.7.2
libvirtd is running on Ubuntu 14.04
The error happens when running vagrant remotely on either Ubuntu or MacOSX

**Comment by pronix** [comment]
require more information
set ```VAGRANT_LOG=debug```
and show ```vagrant box list```

**Comment by jcsalem** [comment]
Okay... It looks like I have to have a copy of the box on the remote machine as well as the machine running libvirtd.  I copied the box over to the ~/vagrant.d/boxes directory on the remote machine and it works now.
