### ISSUE TITLE
id_ssh_key_file always prepends ${HOME}/.ssh

### ISSUE THREAD

**Issue by jcsalem** [pradels/vagrant-libvirt#335]
I have two issues with the :id_ssh_key_file parameter
1) The documentation in README.md doesn't mention that it defaults to 'id_rsa'.  This should be made explicit since it overrode my setting in ~/.ssh/config.  I had to explicitly set id_ssh_key_file to nil to use the IdentifyFile defined in ~/.ssh/config

2) The code around line 248 in lib/vagrant-libvirt/config.rb always prepends $HOME/.ssh/ to the key file name. This should only be done if id_ssh_key_file doesn't contain a slash. To connect to our libvirt server we use a shared private key that is stored in a different directory.
I recommend replacing it with the following code:
```
if @id_ssh_key_file
      # set ssh key for access to libvirt host
      ssh_key_path = @id_ssh_key_file
      ssh_key_path = "#{`echo ${HOME}`.chomp}/.ssh/#{@id_ssh_key_file}" if @id_ssh_key_file !~ /\// 
      uri << "\&keyfile=#{ssh_key_path}"
end
```

**Comment by pronix** [comment]
pr please.

**Comment by jcsalem** [comment]
PR is here: https://github.com/pradels/vagrant-libvirt/pull/337

Note, I'd prefer that @id_ssh_key_file defaulted to nil but I didn't make that change since it would likely break existing libvirt Vagrantfiles.

**Comment by pronix** [comment]
merged

**Comment by jcsalem** [comment]
Thanks!

>
>
