### ISSUE TITLE
Allow emulator to be specified

### ISSUE THREAD

**Issue by spikergit1** [pradels/vagrant-libvirt#340]
Currently ``domain.xml.erb`` does not contain a section for an ``emulator`` when using qemu, such as:

```
<domain type='qemu'>
...
   <os>
     <type arch='ppc64' machine='pseries'>hvm</type>
     <boot dev='cdrom'/>
 </os>
 <devices>
    <emulator>/usr/bin/qemu-system-ppc64</emulator>
 </devices>
</domain>
```

Is there interest in adding an ``emulator`` field to "Domain Specific Options"?

**Comment by pronix** [comment]
if you will implement it - i will merge

**Comment by spikergit1** [comment]
OK will do, I just wanted to test the waters of interest.
