### ISSUE TITLE
Coreos private network

### ISSUE THREAD

**Issue by MCyprien** [pradels/vagrant-libvirt#345]
Hello,
I try to use vagrant libvirt to use kvm as provider. I try to run coreos. I created the box with vagrant mutate and it looks like something is going wrong when I vagrant up. what I am trying to do is a simple private network.
Here is my Vagrantfile :
``` 
Vagrant.configure("2") do |config|
     config.vm.define :test_vm do |test_vm|
      test_vm.vm.box = "coreos-alpha"
      config.ssh.username = 'core'
      config.vm.network "private_network", ip: "172.17.8.100"
     end 
   end 
```
Really simple. I try this with centos and it works. But when I try to use CoreOS I get :
```
==> test_vm: Removing domain...
Bringing machine 'test_vm' up with 'libvirt' provider...
==> test_vm: Creating image (snapshot of base box volume).
==> test_vm: Creating domain with the following settings...
==> test_vm:  -- Name:              vagrant_test_vm
==> test_vm:  -- Domain type:       kvm
==> test_vm:  -- Cpus:              1
==> test_vm:  -- Memory:            512M
==> test_vm:  -- Base box:          coreos-alpha
==> test_vm:  -- Storage pool:      default
==> test_vm:  -- Image:             /var/lib/libvirt/images/vagrant_test_vm.img
==> test_vm:  -- Volume Cache:      default
==> test_vm:  -- Kernel:
==> test_vm:  -- Initrd:
==> test_vm:  -- Graphics Type:     vnc
==> test_vm:  -- Graphics Port:     5900
==> test_vm:  -- Graphics IP:       127.0.0.1
==> test_vm:  -- Graphics Password: Not defined
==> test_vm:  -- Video Type:        cirrus
==> test_vm:  -- Video VRAM:        9216
==> test_vm:  -- Keymap:            en-us
==> test_vm:  -- Command line :
==> test_vm: Starting domain.
==> test_vm: Waiting for domain to get an IP address...
==> test_vm: Waiting for SSH to become available...
    test_vm:
    test_vm: Vagrant insecure key detected. Vagrant will automatically replace
    test_vm: this with a newly generated keypair for better security.
    test_vm:
    test_vm: Inserting generated public key within guest...
    test_vm: Removing insecure key from the guest if its present...
    test_vm: Key inserted! Disconnecting and reconnecting using new SSH key...
==> test_vm: Starting domain.
==> test_vm: Waiting for domain to get an IP address...
==> test_vm: Waiting for SSH to become available...
==> test_vm: Creating shared folders metadata...
==> test_vm: Rsyncing folder: /home/mac/vagrant/ => /vagrant
==> test_vm: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
ifconfig  172.17.8.100 netmask 255.255.255.0

Stdout from the command:

Stderr from the command:

SIOCSIFNETMASK: No such device
```

As it works with centos I think it's a problem with my CoreOS box but I don't really know if I must contact libvirt or mutate.

**Comment by pronix** [comment]
try to specify device name or add support of networkd to vagrant

**Comment by MCyprien** [comment]
I know the syntax is not correct and the device name is missing but I don't run the command, vagrant do it. The question is why does this bug happen with CoreOS.

Now, I tried to add :device=> "eth1" to the vagrantfile but the same issue appears. It look like vagrant doesn't find the device before running the ifconfig. 
I am not expert with vagrant and if I am missing a point please help me but what I don't understand it's the fact that it works with centos64 but not with coreos. It might be a problem with vagrant mutate which didn't convert correctly the box but I don't know how to be sure of that.

**Comment by pronix** [comment]
coreOS use other name patern then ethX

**Comment by MCyprien** [comment]
no It have ethX and other device too such as docker0 but It worked perfectly under virtualbox and not anymore with kvm that's why I created an issue

**Comment by pronix** [comment]
Share you box

**Comment by MCyprien** [comment]
I downloaded the CoreOS box for virtualbox:
http://alpha.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json
and used vagrant mutate on it.
To do it you may have to change ~/.vagrant.d/boxes/coreos-alpha/XXX to ~/.vagrant.d/boxes/coreos-alpha/0

**Comment by pronix** [comment]
Ok. I will check evening

**Comment by MCyprien** [comment]
thank you very much

**Comment by MCyprien** [comment]
It's not a problem with vagrant mutate I created a new box from coreos kvm and I still got the same issue... I don't think the bug come from coreos itself because it works when I run my vm ddirectly on kvm using this tuto :
https://coreos.com/docs/running-coreos/platforms/qemu/

**Comment by pronix** [comment]
may be. Check it later

**Comment by pronix** [comment]
require remove 
```
config.vm.network "private_network", ip: "172.17.8.100"
```
be default ip address accepted from dhcp.
docker working perfect. but for etcd exist bug in ```vagrant-1.7.2/plugins/guests/coreos/cap/configure_networks.rb:64``` or in coreOS - so clustering with alpha not working.

i working very active with Atomic - try it. looks for me more stable

**Comment by MCyprien** [comment]
ok thank you for your help, i will close the issue as it doesn't come from vagrant libvirt.
