### ISSUE TITLE
Give more people write access?

### ISSUE THREAD

**Issue by sciurus** [pradels/vagrant-libvirt#348]
It seems like vagrant-libvirt could use more people with the ability to merge changes, especially since I am not a very active reviewer anymore. @pradels and @pronix  what do you think?

@purpleidea or @strzibny would either of you be interested in having write access to this repository? Do you know anyone else who you think should have it?

**Comment by pronix** [comment]
I don't believe in democracy. But if somebody will write a lot and pull request will bottleneck - i will agree.

**Comment by purpleidea** [comment]
@sciurus I would be interested, assuming we can all have consensus on how to get things in.

**Comment by strzibny** [comment]
I would too, but I don't expect changing anything without PR in foreseenable future.

**Comment by obnoxxx** [comment]
Why does giving more people write access imply not merging upon pull request any more? Isn't it rather about more people being able to treat pull requests? :)

**Comment by infernix** [comment]
I hope at some point we can move this repo to an organisation; until that time we are dependent on pradels for access control. But I'm closing this as it doesn't seem relevant as an open issue at this point, feel free to comment/reopen if you disagree :+1:

**Comment by sciurus** [comment]
I'm glad to see all the recent activity here! Agreed, not a relevant issue anymore.
