### ISSUE TITLE
Call to virDomainCreateWithFlags failed: Unable to get index for interface eth0: No such device

### ISSUE THREAD

**Issue by alff** [pradels/vagrant-libvirt#349]
Hi guys.
Just faced the problem with spinning up new VM. I want to provision new vm with single private net. But the problem is if i specify ip for host it fails. 

vagrant up mn101
Bringing machine 'mn101' up with 'libvirt' provider...
==> mn101: Starting domain.
There was an error talking to Libvirt. The error message is shown
below:

Call to virDomainCreateWithFlags failed: Unable to get index for interface eth0: No such device

But if i didn't specify any net it starts ok with attached default libvirt net.

Part of my Vagrantfile config:
...
  config.vm.define "mn101" do |node|
    node.vm.box = "centwos"
    node.vm.hostname = "mn101"
    node.ssh.username = "vagrant"
    node.ssh.password = "vagrant"
    node.vm.synced_folder './', '/vagrant', type: 'rsync'
    config.vm.provider :libvirt do |libvirt|
      libvirt.memory = 2048
      libvirt.nested = true
      libvirt.cpus = 2
      libvirt.driver = "kvm"
      libvirt.connect_via_ssh = false
      libvirt.username = "root"
      libvirt.storage_pool_name = "default"
      libvirt.nic_model_type = "igb"
    end
    node.vm.network "private_network", ip: "192.168.122.101", :libvirt__network_name => "default"
  end

Host OS: centos 7.0
libvirt 1.2.8
vagrant 1.7.2
vagrant-libvirt 0.0.26

Any thoughts?

**Comment by pronix** [comment]
require more information
set ```VAGRANT_LOG=debug```

**Comment by alff** [comment]
@pronix sure, here is gist:
https://gist.github.com/alff/62142bf8fbe923f236bb

**Comment by pronix** [comment]
sorry. i can't repeat error.
provide server with this error - i will try on it.

**Comment by alff** [comment]
Unfortunately this is a private cloud without direct access from outside. But i could run commands if you provide them for me and i send the output. sorry for this

**Comment by alff** [comment]
Some extra-details.
I compared 2 generated libvirt xml and found next things.

1 node (successfully provisioned without any defined ips or nets in Vagrantfile):
...
<interface type='network'>
      <mac address='52:54:00:e0:67:3a'/>
      <source network='vagrant-libvirt'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </interface>
...

2nd node(failed with defined private ip):
...
    <interface type='network'>
      <mac address='52:54:00:f8:b2:29'/>
      <source network='vagrant-libvirt'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </interface>
    <interface type='direct'>
      <mac address='52:54:00:c6:be:cd'/>
      <source dev='eth0' mode='bridge'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </interface>
...

My host doesn't have eth0 interface. But i assume that interface name should be defined for guest system. So my question is: what is the device 'direct'? And why it's here?

**Comment by alff** [comment]
Seems that i've fixed this situation. But let me ask another question:
may i change default gateway for VMs? When i spinning up new VM first interface always obtains by default libvirt net. So the problem is: if i define public net for VM i can't reach this node from outside because default route on VM goes over first (private) interface.

guest vm:
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:6d:bf:8b brd ff:ff:ff:ff:ff:ff
    inet 192.168.121.245/24 brd 192.168.121.255 scope global eth0
    inet6 fe80::5054:ff:fe6d:bf8b/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:24:42:4c brd ff:ff:ff:ff:ff:ff
    inet 10.44.3.191/20 brd 10.44.15.255 scope global eth1
    inet6 fe80::5054:ff:fe24:424c/64 scope link 
       valid_lft forever preferred_lft forever

routes:
$ netstat -rn
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
192.168.121.0   0.0.0.0         255.255.255.0   U         0 0          0 eth0
10.44.0.0       0.0.0.0         255.255.240.0   U         0 0          0 eth1
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 eth1
0.0.0.0         192.168.121.1   0.0.0.0         UG        0 0          0 eth0

Vagrant net config for guest:
...
node.vm.network :public_network, :dev => "br0", :mode => "bridge", :type => "bridge", ip: "10.44.3.191", :netmask => "255.255.240.0"
...

**Comment by alff** [comment]
So ok. I've also fixed situation with default GW for vagrant. Probably it would be helpful for someone who faced same problem.

I've used workaround script from this issue:
https://github.com/mitchellh/vagrant/issues/2389

"
...
config.vm.network :public_network, ip: "192.168.0.50"     # with static IP, useful for server sharing

# IP address of your LAN's router
default_router = "192.168.0.1"

# change/ensure the default route via the local network's WAN router, useful for public_network/bridged mode
config.vm.provision :shell, :inline => "ip route delete default 2>&1 >/dev/null || true; ip route add default via #{default_router}"

"

also need add extra option with 'reload' command:
vagrant reload --provision

otherwise simple 'reload' rollback your changes with gateway and your guest become inaccessible from outside again.

cheers

**Comment by pronix** [comment]
looks like was required fix you host interface name.

**Comment by timhughes** [comment]
@alff What did you end up doing to fix the "Call to virDomainCreateWithFlags failed: Unable to get index for interface eth0: No such device" issue. I have the same problem

**Comment by narkisr** [comment]
Same issue here, its not fixed

**Comment by jakobadam** [comment]
When using vagrant-libvirt on my Ubuntu laptop with wireless, the interface is obviously not named eth0. I had to rename my wireless interface to eth0 in order to work around the 'Unable to get index for interface eth0: No such device'.

If you forgot how to rename the interface on Ubuntu:

Create a file `/etc/udev/rules.d/70-rename-wireless.rules` and add the following

    SUBSYSTEM=="net", ACTION=="add", ATTR{address}=="ff:ff:ff:ff:ff:ff", NAME="eth0"

Replace ff:ff:ff:ff:ff:ff with your mac-address.

kind regards,
Jakob

**Comment by activedecay** [comment]
I followed the README.md example at the root of the repo, which worked for me
```
    test_vm1.vm.network :public_network,
      :dev => "virbr0",
      :mode => "bridge",
      :type => "bridge"
```

**Comment by jlegido** [comment]
I tried [narkisr](https://github.com/vagrant-libvirt/vagrant-libvirt/issues/349#issuecomment-141668443) solution but I still get the same error.

Looks like it's completely ignoring the "dev" flag.

Below my vagrant file:

```
Vagrant.configure("2") do |config|
  config.vm.define :test_vm do |test_vm|
    test_vm.vm.box = "debian/testing64"
    test_vm.vm.network "public_network", ip: "10.251.0.100", bridge: "br-76c585f71c1f", dev: "br-76c585f71c1f"
  end
end
```
Any help will be appreciated.
Thanks

**Comment by MikePadge** [comment]
Just for future reference because I ended up here like @jlegido 

Make sure you `vagrant destroy` your up cache when you add the :dev device name properly. If you don't, that broken run cache will still attempt to pull the old network device name.
