### ISSUE TITLE
vagrant box remove leaves backing store image in libvirt

### ISSUE THREAD

**Issue by swiftgist** [pradels/vagrant-libvirt#350]
BTW, Excellent plugin.  

This issue may be more of a request for a warning for the user.  I am using Opensuse 13.2 with vagrant 1.7.2, libvirt 1.2.9 and vagrant-libvirt 0.0.26.  I had been using Kiwi to generate Vagrant boxes and could not figure out why my vm was missing the changes after a 'vagrant up'.

Running

`vagrant box add Vagrant-box.json`

does not create the base image in the libvirt pool.  Once I ran vagrant up for a simple configuration, both the original box is pushed to libvirt and a new image is created for this configuration.  This image uses the original image as a qcow2 backing store.  This is ideal.

Now, my original box wasn't ideal so I regenerated a new box with Kiwi.  I then run

`vagrant destroy `
`vagrant box remove Vagrant-box`

The problem is that the `vagrant destroy` removes the image in libvirt pool for the actual vm, but the `vagrant box remove` does not remove the original image used as a backing store.  When I do a subsequent 

`vagrant box add Vagrant-box.json`

I believe I have added a new base image, but this is not the case.  I repeated this twice to verify.  As a result, I kept looking for the problem elsewhere until I started mounting qcow2 images to figure out what was happening.

I'll guess that you may not want to remove a base image from the libvirt pool since other images could be using it.  For that, I would ask that `vagrant box remove` give a warning that the base image in the libvirt pool is not removed.  Another possibility is having `vagrant box add` fail if the image already exists.    The workaround is `virsh vol-delete --pool default <Base_Image.img>`.  However, either of those warnings would have helped.

**Comment by pronix** [comment]
thansk. it is in progress.

**Comment by pronix** [comment]
https://github.com/pradels/vagrant-libvirt/issues/85

**Comment by pronix** [comment]
looks like any solution of this issue will generate more problem. so -any new ideas and comments to issue n85

**Comment by swiftgist** [comment]
Hi Pronix,
  I was simply hoping for an exception if the box already exists and does not match the same box in the ~/vagrant.d directory.  In handle_box_image.rb line 137, the return is searching for the matching volume and will not upload the new image.  I don't know if libvirt exposes file sizes of images (not perfect, but an improvement over the current situation).  Raising an exception based on a failed image comparison just prior to the find_matching would do the trick.  Or simply removing the image from libvirt if the comparison fails and let the rest of the logic work as normal.

  If removing the image causes cascading failures and other issues, then a message "Basebox image mismatch - use "virsh vol-delete _image_"  would be helpful.  Sorry that I didn't see issue #85.

Eric

**Comment by pronix** [comment]
i will check version. Should be helpful
