### ISSUE TITLE
[PATCH] read_ssh_info mishandles multiple leases for the same machine from dnsmasq

### ISSUE THREAD

**Issue by dcbw** [pradels/vagrant-libvirt#353]
If DHCP is used as the addressing mode of the VM it may receive various IP addresses over time.  Thus dnsmasq can report all these addresses for a single machine, which gives us:

`addresses {:public=>["192.168.121.180\n192.168.121.184\n192.168.121.183\n192.168.121.182"], :private=>["192.168.121.180\n192.168.121.184\n192.168.121.183\n192.168.121.182"]}`

This causes the most problems when NFS is used as the shared folder mechanism, as the IP addresses pile up and a malformed /etc/exports is written.  This in turn causes sequences of vagrant halt / vagrant up to receive read-only NFS exports due to the bad format:

    # VAGRANT-BEGIN: 1000 d943c68a-330b-4cb8-8711-53506a6c176e
    "/home/user/folder" 192.168.121.52
    192.168.121.51(rw,no_subtree_check,all_squash,anonuid=1000,anongid=1000,fsid=3414715164)
    # VAGRANT-END: 1000 d943c68a-330b-4cb8-8711-53506a6c176e

It seems that Vagrant expects that the value returned by read_ssh_info is just a single IP address, which seems reasonable.

Something like this appears to work for both the single case and the multi-IP case:

         # Get IP address from dnsmasq lease file.
          ip_address = nil
          domain.wait_for(2) {
            addresses.each_pair do |type, ip|
              if ip[0] != nil
                # Multiple leases are separated with a newline, return only
                # the most recent address
                nl_idx = ip[0].index("\n")
                if nl_idx.nil?
                  ip_address = ip[0] if ip[0] != nil
                else
                  ip_address = ip[0][0, nl_idx]
                end
              end
            end
            ip_address != nil
          }
          raise Errors::NoIpAddressError if not ip_address

**Comment by dcbw** [comment]
Or even:

          # Get IP address from dnsmasq lease file.
          ip_address = nil
          domain.wait_for(2) {
            addresses.each_pair do |type, ip|
              if ip[0] != nil
                # Multiple leases are separated with a newline, return only
                # the most recent address
                nl_idx = ip[0].index("\n")
                nl_idx = ip[0].length if nl_idx.nil?
                ip_address = ip[0][0, nl_idx]
              end
            end
            ip_address != nil
          }
          raise Errors::NoIpAddressError if not ip_address

**Comment by pronix** [comment]
thanks for patch. it will accepted as soon as i will find button "Merge"

**Comment by dcbw** [comment]
Pull request created here https://github.com/pradels/vagrant-libvirt/pull/355

**Comment by pronix** [comment]
https://github.com/pradels/vagrant-libvirt/pull/356
