### ISSUE TITLE
Gateway on other address than .1

### ISSUE THREAD

**Issue by fxkr** [pradels/vagrant-libvirt#357]
I want to model a production network which has hosts with static IP addresses and .254 for the gateway. Unfortunately, vagrant-libvirt has .1 hardcoded. There should be an option to override this.

lib/vagrant-libvirt/action/create_networks.rb:
```
@interface_network[:ip_address] = net.to_range.begin.succ
```
```
            start_address = net.to_range.begin.succ.succ
```

**Comment by pronix** [comment]
pr please
