### ISSUE TITLE
libvirt is not a recognized compute provider

### ISSUE THREAD

**Issue by mdimjasevic** [pradels/vagrant-libvirt#362]
It all worked just fine until recently, but since then I cannot use most of Vagrant operations. If I try to vagrant-up a machine, I get the following:

$ vagrant up
Bringing machine 'master' up with 'libvirt' provider...
/home/marko/.vagrant.d/gems/gems/fog-core-1.30.0/lib/fog/compute.rb:66:in `new': libvirt is not a recognized compute provider (ArgumentError)
        from /home/marko/.vagrant.d/gems/gems/vagrant-libvirt-0.0.26/lib/vagrant-libvirt/action/connect_libvirt.rb:38:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
        from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
        from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
        from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:196:in `action_raw'
        from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:173:in `block in action'
        from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:440:in `lock'
        from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:161:in `call'
        from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:161:in `action'
        from /usr/lib/ruby/vendor_ruby/vagrant/batch_action.rb:82:in `block (2 levels) in run'

My hunch is this has to do with `dnsmasq`, which I upgraded in the meantime.

**Comment by Aletz-Morales** [comment]
Same problem on Vagrant 1.7.2 and vagrant-libvirt 0.0.26

**Comment by mdimjasevic** [comment]
In case needed, here are some versions. Vagrant is at 1.6.5 and vagrant-libvirt is at 0.0.26. This is on Debian GNU/Linux 8 (Jessie).

**Comment by jwmatthews** [comment]
I'm seeing similar issue (Fedora 20, vagrant 1.7.2, vagrant-libvirt 0.26). 

On my box, fog was recently upgraded to 1.30 while installing vagrant-aws.
Now when using --provider=libvirt I'm seeing:

$ vagrant up --provider=libvirt
/home/jmatthews/.vagrant.d/gems/gems/fog-core-1.30.0/lib/fog/compute.rb:66:in `new': libvirt is not a recognized compute provider (ArgumentError)
	from /home/jmatthews/.vagrant.d/gems/gems/vagrant-libvirt-0.0.26/lib/vagrant-libvirt/action/connect_libvirt.rb:38:in `call'

$ vagrant plugin list
vagrant-aws (0.6.0)
vagrant-hostmanager (1.5.0)
vagrant-libvirt (0.0.26)
vagrant-share (1.1.3, system)

$ rpm -qa | grep vagrant
vagrant-1.7.2-1.x86_64

Looks like fog-1.30 has moved libvirt support into a separate gem, fog-libvirt.

Below commit should resolve the problem, but I don't see it in a release of vagrant-libvirt yet:
   https://github.com/pradels/vagrant-libvirt/commit/749b431bc85a6a94dbda77e95e5e005b335953a7

**Comment by pronix** [comment]
downgrade your fog to 1.29 OR  install fog-libvirt by 
```
vagrant plugin install fog-libvirt
```

**Comment by pronix** [comment]
or update version of vagrant-libvirt

**Comment by jwmatthews** [comment]
@pronix thank you for the new release of vagrant-libvirt 0.27.    

I confirmed your suggestion of "vagrant plugin install fog-libvirt" resolved my issue.
