### ISSUE TITLE
Mount NFS share through bridged public network

### ISSUE THREAD

**Issue by thefallentree** [pradels/vagrant-libvirt#366]
Hi,

I know current implementation uses host-only network to mount NFS share , that sure doesn't work in remote libvirt server mode.

But, we have a specific environment that we want to have a bridged network "eth1" that can connect back to local vagrant machine, mounting NFS should be possible.  Can you add support for this usage?

Thanks

**Comment by pronix** [comment]
hello.
i can accept pull request.

**Comment by thefallentree** [comment]
Yes, we are trying to see if we will be able to read machine outbound IP and directly use that in prepare_nfs_settings.rb

One more issue we found is eth1 (bridged network) is not properly setup on machine up...

**Comment by thefallentree** [comment]
We've solved both issue, and we are able to  have  mount NFS shares through "public" bridge network .

**Comment by pronix** [comment]
super.waiting you pr.
