### ISSUE TITLE
Allow use of an existing host bridge interface

### ISSUE THREAD

**Issue by superjamie** [pradels/vagrant-libvirt#380]
Oh my host I have a physical interface `eth0` which is already in a bridge `br0`.

I already have some libvirt-managed KVM VMs which I bridge to my LAN via `br0`. When the VMs start, a `tuntap` interface is added to the host called `vnetX` which is then bridged into `br0`.

I would like to be able to add Vagrant VMs to this pre-existing bridge as well, so that the Vagrant-created VM is networked via tap interface in the same way as the existing VMs.

**Comment by pronix** [comment]
cool. as soon as you implement this feature i will happy to accept it.

**Comment by knoorke** [comment]
Had the same problem...
This is how I solved it:

machine.vm.network :public_network,
        :dev => 'br0',
        :type => 'bridge'


:type sets the <interface type=...> parameter in the domains xml description. 
:dev sets the <source bridge=...> parameter of the interface. Compare to
https://github.com/pradels/vagrant-libvirt/blob/master/lib/vagrant-libvirt/templates/public_interface.xml.erb
and
https://github.com/pradels/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/create_network_interfaces.rb#L68


To be more verbose: Below is an example where libvirt creates a TUN/TAP device and adds it to the specified bridge:
<domain>
...
 <interface type='bridge'>
      <mac address='52:54:00:2a:6b:02'/>
      <source bridge='br0'/>
      <target dev='vnet0'/>
      <model type='rtl8139'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
 </interface>
...
</domain>

For me, it sufficed to use the public_network xml template. It lacks the target, alias and address tags, but works nonetheless.

**Comment by mbassett** [comment]
I was able to create the bridge interface using something similar to what you did above, but for some reason I still get an eth0 interface to the default nat interface.

    <interface type='network'>
      <mac address='52:54:00:1c:12:99'/>
      <source network='vagrant-libvirt' bridge='virbr1'/>
      <target dev='vnet3'/>
      <model type='virtio'/>
      <alias name='net0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </interface>
    <interface type='bridge'>
      <mac address='52:54:00:be:e6:9f'/>
      <source bridge='br0'/>
      <target dev='vnet4'/>
      <model type='virtio'/>
      <alias name='net1'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </interface>

and because i get the default nat interface on eth0 vagrant can't do anything since the interface never comes up, and eth1 doesn't get built since it's missing ifcfg-eth1 files.

**Comment by mbassett** [comment]
config.vm.define :test_vm do |test_vm|
    test_vm.vm.box = "mycentosvagrant"
    test_vm.vm.network :public_network, :dev => "br0", :type => "bridge"
  end

**Comment by fbrier** [comment]
I have been reading all the different configurations suggested including the:
```
machine.vm.network :public_network,
:dev => 'br0',
:type => 'bridge'
```
with no success.  I have been using KVM/libvirt for years, setting up lots of different VMs with a bridge to the rest of my network, most using Chef.  This is my first time trying to use Vagrant.  This should be one of the most common use cases, yet it seems that everyone is banging their heads against the wall.  It would be nice if there were a set of example VagrantFile(s) for the most common configurations, one of which should be a VM that has a bridged interface to the network the host is connected to.

I have created a custom Ubuntu 14.04 LTS box which deploys, but it only has an eth0 interface to the default virtual network.  Attempting to add the bridged interface either does nothing, says it can't find the eth1 interface, gets a virDomainCreateWithFlags failed error, gets stuck at Waiting for SSH, or any of a number of other errors.

**Comment by fbrier** [comment]
I finally got it working.  The above configuration is correct.  My problem was missing an additional entry in the /etc/network/interfaces file of the guest image (Ubuntu 14.04 LTS).  By adding:
```
# The bridge network interface
auto eth1
iface eth1 inet dhcp
```
the eth1 interface was found and used.  The problem occurred because the Vagrant required private network management interface was using eth0.

**Comment by infernix** [comment]
This is working just fine with:
```ruby
machine.vm.network :public_network,
:dev => 'br0',
:type => 'bridge'
```
In vagrant 1.8.1. It even creates the `eth1` stanza to bring it up at boottime.

So, closing as I don't see a bug here.

**Comment by christianbueno1** [comment]
I am getting this Error:
```
==> default: Starting domain.
/usr/share/gems/gems/fog-libvirt-0.9.0/lib/fog/libvirt/requests/compute/vm_action.rb:7:in `create': Call to virDomainCreateWithFlags failed: /usr/libexec/qemu-bridge-helper --use-vnet --br=br0 --fd=31: failed to communicate with bridge helper: stderr=access denied by acl file (Libvirt::Error)
: Transport endpoint is not connected
```

Host: fedora 38
```
❯ nmcli dev status
DEVICE   TYPE      STATE                   CONNECTION            
br0      bridge    connected               br0                   
lo       loopback  connected (externally)  lo                    
vnet0    tun       connected (externally)  vnet0                 
virbr0   bridge    connected (externally)  virbr0                
enp0s25  ethernet  connected               Ethernet connection 2 
```
```
❯ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp0s25: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel master br0 state UP group default qlen 1000
    link/ether 00:22:4d:a6:4b:e9 brd ff:ff:ff:ff:ff:ff
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:17:1e:53 brd ff:ff:ff:ff:ff:ff
5: br0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 00:22:4d:a6:4b:e9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.129/24 brd 192.168.1.255 scope global noprefixroute br0
       valid_lft forever preferred_lft forever
    inet6 fe80::443:557e:949b:a787/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
6: vnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br0 state UNKNOWN group default qlen 1000
    link/ether fe:54:00:a3:dc:e4 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::fc54:ff:fea3:dce4/64 scope link 
       valid_lft forever preferred_lft forever
  ~/Documents/vagrant-projects/rocky9        
```

**vagrantfile**
```
Vagrant.configure("2") do |config|
  config.vm.box = "generic/rocky9"
  config.vm.network :public_network, :dev => 'br0', :type => 'bridge'
end
```

**Comment by christianbueno1** [comment]
After disconnect using the KDE plasma GUI the virbr0 device , how can I reconnect it? The device dissappeared from there.
