### ISSUE TITLE
Boot order option

### ISSUE THREAD

**Issue by dc-bradwadsworth** [pradels/vagrant-libvirt#381]
Would it be possible to add the qemu -boot option to the domain options? For example,
```
domain.boot = "order=nc"
```

**Comment by pronix** [comment]
* `cmd_line` - Arguments passed on to the guest kernel initramfs or initrd to use. Equivalent to qemu `-append`.
from README

**Comment by dc-bradwadsworth** [comment]
This is not a kernel option, it is a bios option.

**Comment by pronix** [comment]
I see. you can implement it.
