### ISSUE TITLE
Additional images could/should be listed

### ISSUE THREAD

**Issue by justinc1** [pradels/vagrant-libvirt#394]
It would be nice if more complete list of vagrant images/boxes would be shown in Readme.md. The "vagrant box add centos64 http://citozin.com/centos64.box" made me to try something like trusty64.box for current LTS ubuntu, but - 404. 

Now it seems sensible choice is https://atlas.hashicorp.com/naelyn/boxes/ubuntu-trusty64-libvirt.

**Comment by pronix** [comment]
use mutate for convert
