### ISSUE TITLE
Remove stale volume fails with undefined method `name' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by infernix** [pradels/vagrant-libvirt#399]
This looks to be introduced in or after 0.30, no such problem with 0.29:

<pre>=> foo: Remove stale volume...
/home/infernix/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/remove_stale_volume.rb:26:in `call': undefined method `name' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/infernix/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /home/infernix/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/destroy/command.rb:31:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:226:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:220:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:220:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/destroy/command.rb:30:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
	from /opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'
</pre>

**Comment by discordianfish** [comment]
Just ran into the same problem.
It looks like it happens only if the VMs are in some special state (volume created but VM not started).

**Comment by infernix** [comment]
Haven't seen this in ages, closing.

**Comment by furlongm** [comment]
I am seeing this on 0.40.0. If I should open a new issue, please let me know. It occurs when issuing a `vagrant destroy -f` and some of the VMs do not exist.

```==> vm6: Remove stale volume...
/home/travis/.vagrant.d/gems/2.3.4/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/remove_stale_volume.rb:26:in `call': undefined method `name' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /home/travis/.vagrant.d/gems/2.3.4/gems/vagrant-libvirt-0.0.40/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:227:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:202:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:631:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:188:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/machine.rb:188:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/commands/destroy/command.rb:31:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/plugin/v2/command.rb:229:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/plugins/commands/destroy/command.rb:30:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:138:in `<main>'```

**Comment by MarcoR83** [comment]
> Haven't seen this in ages, closing.

well, I did!  Arch-Linux, Vagrant 2.2.6, ruby 2.6.5p114 (2019-10-01 revision 67812), vagrant-libvirt (0.0.45, global).

what to-do to get rid of the VM? delete it manually? -.-

`vagrant destroy
==> k8s-3: Remove stale volume...
Traceback (most recent call last):
35: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
34: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in `action'
33: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/machine.rb:195:in `call'
32: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/environment.rb:613:in `lock'
31: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/machine.rb:209:in `block in action'
30: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/machine.rb:238:in `action_raw'
29: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `run'
28: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in `busy'
27: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
26: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'
25: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
24: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
23: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
22: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
21: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
20: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
19: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
18: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
17: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
16: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builtin/call.rb:53:in `call'
15: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `run'
14: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/util/busy.rb:19:in `busy'
13: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/runner.rb:102:in `block in run'
12: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builder.rb:116:in `call'
11: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
10: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:121:in `block in finalize_action'
9: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
8: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
7: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
6: from /home/marco/.vagrant.d/gems/2.6.5/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
5: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
4: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builtin/after_trigger.rb:26:in `call'
3: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
2: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/builtin/before_trigger.rb:23:in `call'
1: from /opt/vagrant/embedded/gems/gems/vagrant-2.2.6/lib/vagrant/action/warden.rb:50:in `call'
/home/marco/.vagrant.d/gems/2.6.5/gems/vagrant-libvirt-0.0.45/lib/vagrant-libvirt/action/remove_stale_volume.rb:26:in `call': undefined method `name' for nil:NilClass (NoMethodError)`

**Comment by brianjmurrell** [comment]
Can we reopen this please?  I am seeing it on Vagrant 2.2.9 with the libvirt provider.

**Comment by electrofelix** [comment]
@brianjmurrell I think best to open a new one and reference this as it's been so long since it was originally opened
