### ISSUE TITLE
network lookup may fail for very isolated networks

### ISSUE THREAD

**Issue by mperedim** [pradels/vagrant-libvirt#402]
Network lookup may fail for veryisolated networks since they lack an IP address. Here is a typical error message: 

Address 169.254.0.99 does not match with network name R8TP-1000-atmdata.
Please fix your configuration and run vagrant again.

I've successfully tested the following fix (for legal reasons, I'd prefer not to go through the process of a pull request) 

```
$diff -u2 ./lib/vagrant-libvirt/action/create_networks.rb.orig ./lib/vagrant-libvirt/action/create_networks.rb
--- ./lib/vagrant-libvirt/action/create_networks.rb.orig        2015-06-24 07:44:08.354258144 +0300
+++ ./lib/vagrant-libvirt/action/create_networks.rb     2015-06-24 08:06:31.545276759 +0300
@@ -137,4 +137,11 @@
             end
           end
+          # if network is veryisolated, search by name instead
+          if @options[:libvirt__forward_mode] == "veryisolated"
+            if lookup_network_by_name(@options[:network_name])
+              @interface_network = lookup_network_by_name(@options[:network_name])
+              @logger.debug @interface_network
+            end
+          end

           if @interface_network[:created]
```

Any chance we can merge the above? 

P.S. I've also noted that "veryisolated" networks still require an ip address in Vagrantfile; I'll eventually fix this as well

**Comment by R2ZER0** [comment]
A heads up, you might be interested in: https://github.com/pradels/vagrant-libvirt/pull/417

**Comment by joejulian** [comment]
For example, take two (or more) virtual machines. 

The first VM is on a natted 'nat' network, and *also* on a 'veryisolated' network where it VM provides dhcp and dns for any additional machines.

        vm_config.vm.network 'private_network',
                             auto_config: false,
                             ip: '192.168.50.0,
                             mac: '00006C6999A0',
                             libvirt__dhcp_enabled: false,
                             libvirt__network_name: 'natted_network'

        vm_config.vm.network 'private_network',
                             auto_config: false,
                             ip: 192.168.10.0,
                             mac: '00016C6999A0',
                             libvirt__dhcp_enabled: false,
                             libvirt__network_name: 'veryisolated_network',
                             libvirt__forward_mode: 'veryisolated'


All other machines *only* connect to the veryisolated network.

        vm_config.vm.network 'private_network',
                             auto_config: false,
                             ip: 192.168.10.0,
                             mac: '00016C69BEEF',
                             libvirt__dhcp_enabled: false,
                             libvirt__network_name: 'veryisolated_network',
                             libvirt__forward_mode: 'veryisolated'

The networks are correctly created and defined as such:

```
<network connections='1' ipv6='yes'>
  <name>natted_network</name>
  <uuid>4b752626-300e-4ee0-9d5b-966637ff8f56</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr1' stp='on' delay='0'/>
  <mac address='52:54:00:46:3b:2d'/>
  <ip address='192.168.50.1' netmask='255.255.255.0'>
  </ip>
</network>
```

```
<network connections='1' ipv6='yes'>
  <name>veryisolated_network</name>
  <uuid>7f83ee84-66e8-4313-b01d-edac2716ab24</uuid>
  <bridge name='virbr2' stp='on' delay='0'/>
  <mac address='52:54:00:27:91:f9'/>
</network>
```

When the next VM attempts to boot, it fails with:
```
Address 192.168.10.0 does not match with network name veryisolated_network.
Please fix your configuration and run vagrant again.
```

The expected behavior is that the network would match by name since there is no ip address assigned.
