### ISSUE TITLE
Error with architecture i386

### ISSUE THREAD

**Issue by dancn** [pradels/vagrant-libvirt#407]
The doc suggest to use:
```
domain.machine_arch = "i386"
```

But leads to:
```
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unsupported configuration: Unknown architecture i386 
```

If I use i686 no errors, but the kernel-32 does not boot with a
backtrace and the kernel-64 does not boot and does not print anything.

Note that there is no qemu-system-i686 on my host. Only
qemu-system-x86_64 and qemu-system-i386 are present.

I used "ubuntu/trusty32" and "ubuntu/trusty64" virtualbox boxes
migrated with vagrant-migrate.

My goal is to get a 32 bit domain up and running. A workaround is
manually edit the conf and add:

```
<cpu mode='custom' match='exact'>
   <model fallback='allow'>kvm32</model>
</cpu>
```

Im not sure if this is also possible by using the cpu_mode. Setting it
(with nested true) gives:

```
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unsupported configuration: Invalid mode attribute 'kvm32'
```

**Comment by Demonsthere** [comment]
Hey,
The same issue happens if I want to set the arch to arm 
```
domain.machine_arch = "arm"
```
produces
```
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: unsupported configuration: Unknown architecture arm
```

My use case is:
I have a working arm VM that is called 'by hand' with plain qemu and shell wrappers, and I would like to package it and run as a vagrant box

**Comment by infernix** [comment]
@Demonsthere  Code was added in 0.0.33 so make sure you are on that version.

That being said. "arm" is not a valid machine_arch. Try like this:

```ruby
         domain.machine_type = 'virt'
         domain.machine_arch = 'armv7l'
         domain.cpu_mode = 'custom'
         domain.cpu_model = 'cortex-a15'
         domain.cpu_fallback = 'allow'
```

Tweak as needed.

@dancn  for 32bits, try: 

```real
    vb.machine_arch = 'i686'
    vb.cpu_mode = 'custom'
    vb.cpu_model = 'qemu32'
    vb.cpu_fallback = 'allow'
    vb.emulator_path = '/usr/bin/qemu-system-i386'
```
