### ISSUE TITLE
IP for management network

### ISSUE THREAD

**Issue by jfcastroluis** [pradels/vagrant-libvirt#409]
Hi,

first all, I want congratulate you for this amazing work! I'm using for a couple months and it's very useful for us :)

I would like assign a IP to each machine in my Vagrantfile for management network. How can I do that?

Thanks in advance!

**Comment by jfcastro** [comment]
I'm trying to code a pull request but I can't find where management interface is build. Some help is welcome :smile:

**Comment by pronix** [comment]
you should create virtual network o libvirt and after that assign vm to this management subnet.

**Comment by jfcastro** [comment]
But I can't configure (afaik) a specific IP in my Vagrantfile for management interface (neither mac address to send IP from DHCP).

Can I configure IP to management network interface? 

Thanks!

**Comment by pronix** [comment]
no

**Comment by jfcastro** [comment]
And is it interesting to implement it?

I try code it but I can't find where management network interfaces is created. I'm not a developer, I'm sysadmin and it's difficult for me :disappointed: 

It was very useful for us! :smiley: 

Thanks

**Comment by pronix** [comment]
you should create virtual network o libvirt and after that assign vm to this management subnet.

**Comment by timhughes** [comment]
Edit your `vagrant-libvirt` network to have assigned IP to MAC addresses and have a look at #457 for a patch to give the management interface a known MAC address


```
<network connections='2' ipv6='yes'>
  <name>vagrant-libvirt</name>
  <uuid>XXXXXXXXXX-1234-5678-9012-XXXXXXXXXXX</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr1' stp='on' delay='0'/>
  <mac address='52:54:00:b1:51:ff'/>
  <ip address='192.168.121.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.121.2' end='192.168.121.254'/>
      <host mac='52:54:00:A8:79:12' name='foo.example.internal' ip='192.168.121.18' />
      <host mac='52:54:00:A8:79:13' name='bar.example.internal' ip='192.168.121.19' />
    </dhcp>
  </ip>
</network>
```

**Comment by infernix** [comment]
Closing this  since we have a valid solution in last comment. For other static IP assignments, use `private_network`.
