### ISSUE TITLE
machine_virtual_size setting isn't allowed

### ISSUE THREAD

**Issue by PaulDenton** [pradels/vagrant-libvirt#410]
When trying to start a couple of vmss with option machine_virtual_size, vagrant throws up an error:
```
* The following settings shouldn't exist: machine_virtual_size
```

Here's the respective excerpt from one of vm's config blocks from Vagrantfile:
```
...
    app.vm.provider :libvirt do |libvirt|
      libvirt.memory = 6144
      libvirt.cpus = 4
      libvirt.machine_virtual_size = 30
    end
...
```

**Comment by jfcastro** [comment]
Maybe you're running version 0.0.30 and it's not yet implemented.

Make sure tag 0.0.30 is selected in branch dropdown near of repository name in main page of github to read right documentation ;)

**Comment by PaulDenton** [comment]
Yep, you're right. Thanks :) . Closing the issue.
