### ISSUE TITLE
suspend to disk?

### ISSUE THREAD

**Issue by LeoIannacone** [pradels/vagrant-libvirt#411]
Hi,

vagrant suspend does not free RAM.

Is there a way to suspend to disk?

**Comment by jfcastro** [comment]
Hi, Leolannacone.

vagrant suspend is same as suspend in libvirt: like a pause in domain but no freeing resources.

If you want resources are releasing you can halt because save libvirt command is not implemented in vagrant-libvirt ;)

**Comment by mkutsevol** [comment]
Quite a legal use case. I would benefit from it. Switching among projects will retain state but will free resources whine inactive. 
https://docs.vagrantup.com/v2/cli/suspend.html doesn't require to free resources so I will implement is as a domain specific parameter. The default value will keep the current behavior.
Will make a PR soon.

**Comment by mkutsevol** [comment]
@LeoIannacone can you please check the behavior of the 0.0.32 version and close the issue if everything is good for you?
Thank you.

**Comment by infernix** [comment]
As far as I can tell all this was merged in #470 so I'm closing this, feel free to reopen if needed.
