### ISSUE TITLE
vagrant-libvirt-0.0.30 : bug : prepare_nfs_settings.rb:44 gives Array instead of String

### ISSUE THREAD

**Issue by cuky23** [pradels/vagrant-libvirt#412]
I am keen to see this working as I have had install the following to get libvirt working again on el7.

I have found the following seems to get a working install on Centos7

vagrant plugin install --plugin-version 1.6.3.1 nokogiri
vagrant plugin install --plugin-version 0.4 ruby-libvirt
vagrant plugin install --plugin-version 1.16.0 fog
vagrant plugin install --plugin-version 0.0.24 vagrant-libvirt

**Comment by multiart** [comment]
I changed read_host_ip method in prepare_nfs_settings.rb file:

        def read_host_ip(ip)
          UDPSocket.open do |s|
            if(ip.kind_of?(Array))
                s.connect(ip.last, 1)
            else
                s.connect(ip, 1)
            end
            s.addr.last
          end
        end

and it works for vagrant-libvirt version 0.0.30

**Comment by rafaeltuelho** [comment]
Hey @multiart! 
Your code snippet worked fine here. I'm using `RHEL 7.1` and `Vagrant 1.7.4` with `vagrat-libvirt 0.0.30`

Did you made a pull request with this patch?

Thanks!

**Comment by bcambl** [comment]
@rafaeltuelho I ran into this today as well. 
Looks like it was fixed in master a few weeks ago.
