### ISSUE TITLE
Changing hard code adapter count limit from 8 to variable

### ISSUE THREAD

**Issue by skamithi** [pradels/vagrant-libvirt#414]
Hello, 
new to vagrant development and looking for advice on how to [change the line](https://github.com/pradels/vagrant-libvirt/blob/master/lib/vagrant-libvirt/action/create_network_interfaces.rb#L168) in ``find_empty`` that sets the adapter count limit to 8. Don't see where libvirt or qemu sets this limit, if I'm wrong please point me to this information. I hacked the line by changing it to 100 , and I can create a 96 nic linux VM using libvirt tcp tunnel interfaces,  and it seems to work so far. So was thinking of changing this into a variable and having it set to a default of 8. Then define a host specific parameter like
``node.vm.adapter_count => 32`` which would change that variable to 32 so I can configure 32 NICs. This is needed for the work I'm doing with linux based switch VMs. 

What's the vagrant recommended way to make this change and I will do a Pull Request with the advice provided?

**Comment by pronix** [comment]
hello
there is not limits, it is just trick for not huge amount of iterations.
so you can increase it.
I think 100 will not too complicated for ruby

**Comment by skamithi** [comment]
setting it to 100 was just as an experiment. creating a PR to add this as a variable, with a default setting of 8, and  recommendation of 37 if using  cumulus linux VMs in a multi-machine vagrant setup or single machine setup. This matches the capabilities of vagrant virtualbox provider which has a limit of 37 nics, and should hopeful not be too complicated for ruby as far as iterations go, as mentioned earlier.

**Comment by skamithi** [comment]
commits referenced here are from a deleted repo. I deleted my fork of vagrant-libvirt and regenerated again. still learning my way around git. if someone has a suggestion on how to delete the entries completely so it doesn't show up in this issue, please let me know.

**Comment by pronix** [comment]
merged correct.
