### ISSUE TITLE
key in virGetStorageVol must not be NULL

### ISSUE THREAD

**Issue by miminar** [pradels/vagrant-libvirt#424]
When I run:

    vagrant up --provider=libvirt

I get:

    Bringing machine 'openshiftdev' up with 'libvirt' provider...
    ==> openshiftdev: Uploading base box image as volume into libvirt storage...
    /home/miminar/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume_xml': Call to virNetworkCreateXML failed: key in virGetStorageVol must not be NULL (Libvirt::Error)
        from /home/miminar/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume'
        from /home/miminar/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/models/compute/volume.rb:40:in `save'
        from /home/miminar/.vagrant.d/gems/gems/fog-core-1.32.0/lib/fog/core/collection.rb:51:in `create'
        from /home/miminar/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:56:in `block in call'
        from /home/miminar/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:40:in `synchronize'
        from /home/miminar/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_box_image.rb:40:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/miminar/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:24:in `block in call'
        from /home/miminar/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:17:in `synchronize'
        from /home/miminar/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/handle_storage_pool.rb:17:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/miminar/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/set_name_of_domain.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
        from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
        from /usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
        from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
        from /usr/share/vagrant/lib/vagrant/action/builtin/call.rb:53:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /home/miminar/.vagrant.d/gems/gems/vagrant-libvirt-0.0.30/lib/vagrant-libvirt/action/connect_libvirt.rb:18:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /usr/share/vagrant/lib/vagrant/action/warden.rb:34:in `call'
        from /usr/share/vagrant/lib/vagrant/action/builder.rb:116:in `call'
        from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `block in run'
        from /usr/share/vagrant/lib/vagrant/util/busy.rb:19:in `busy'
        from /usr/share/vagrant/lib/vagrant/action/runner.rb:66:in `run'
        from /usr/share/vagrant/lib/vagrant/machine.rb:214:in `action_raw'
        from /usr/share/vagrant/lib/vagrant/machine.rb:191:in `block in action'
        from /usr/share/vagrant/lib/vagrant/environment.rb:516:in `lock'
        from /usr/share/vagrant/lib/vagrant/machine.rb:178:in `call'
        from /usr/share/vagrant/lib/vagrant/machine.rb:178:in `action'
        from /usr/share/vagrant/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

I'm using slightly modified [Vagrantfile](https://github.com/openshift/origin/blob/6f228f3ea9277c137d0b70b5330b9d2ca356ec69/Vagrantfile) from openshift/origin. With line:

      libvirt.storage_pool_name = "vgrant"

Added to `config.vm.provider "libvirt" do |libvirt, override|` block. After the first invocation, following gets created within `vgrant` volume group:

      lvol1                                                 vgrant twi-aotz--   1,46g                                                            0,00   1,07                            
      rhel-server-7.1_vagrant_box_image_0.img               vgrant Vwi-a-tz--  20,00g lvol1                                                      0,00         
With the error message above. After second invocation, the listing changes:

      lvol1                                                 vgrant twi-aotz--   1,46g                                                            0,00   0,98                            
      lvol2                                                 vgrant twi-a-tz--   1,46g                                                            0,00   0,98   
And the error message changes to:

    ==> openshiftdev: Uploading base box image as volume into libvirt storage...
    /home/miminar/.vagrant.d/gems/gems/fog-libvirt-0.0.2/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume_xml': Call to virNetworkCreateXML failed: internal error: Child process (/usr/sbin/lvcreate --name rhel-server-7.1_vagrant_box_image_0.img -L 1529856K --virtualsize 20971520K vgrant) unexpected exit status 5:   Logical volume "rhel-server-7.1_vagrant_box_image_0.img" already exists in volume group "vgrant" (Libvirt::Error)

Version of vagrant plugin:

    Installed the plugin 'vagrant-libvirt (0.0.30)'!

Other RPM versions:

    libvirt-1.2.9.3-2.fc21.x86_64 
    vagrant-1.7.2-9.fc21.1.noarch

**Comment by infernix** [comment]
I've grabbed that Vagrantfile and made a change but could not reproduce. Please retry with latest vagrant and vagrant-libvirt and if it still occurs, reopen the issue.
