### ISSUE TITLE
Vagrant `chef.delete_node` and `chef.delete_client` not executed

### ISSUE THREAD

**Issue by lukas0krupa** [pradels/vagrant-libvirt#434]
Hi guys,

tested with VirtualBox and guys from Sethvargo from Vagrant tried it with VirtualBox and VMVare. (See [6039](https://github.com/mitchellh/vagrant/issues/6039)

When using chef provision, following settings are ignored or not executed and thus Node/Client isn't deleted from Chef server.

```
    chef.delete_node    = true
    chef.delete_client  = true
```

It might be a case that this isn't anything to do with you, but for some reason deletion isn't triggered. 
Vagrant version 1.7.4 and vagrant-libvirt 0.0.30.

Thanks

**Comment by electrofelix** [comment]
I suspect the chef provisoner deletion actions are hooked to a provider specific action that doesn't exist for vagrant-libvirt. I'll look to check later if someone doesn't confirm in the meantime.

**Comment by electrofelix** [comment]
Just checked vagrant-libvirt is missing a call to a ProvisionerCleanup action.
