### ISSUE TITLE
Support for UEFI

### ISSUE THREAD

**Issue by gbriones1** [pradels/vagrant-libvirt#435]
Hi Guys,

Is there any way to include UEFI support? Libvirt has this feature and I have an OS that requires it. Something like:

`libvirt.loader = "UEFI"`

or

`libvirt.ovmf = "/usr/share/OVMF/OVMF.fd"`

Thnks.

**Comment by pronix** [comment]
https://github.com/pradels/vagrant-libvirt/pull/439 :+1:
