### ISSUE TITLE
nwfilter support

### ISSUE THREAD

**Issue by fbrier** [pradels/vagrant-libvirt#519]
Is there a way to create an nwfilter configuration and the ability to assign that named filter to a bridged interface?

**Comment by pronix** [comment]
for example https://github.com/pradels/vagrant-libvirt/pull/515

**Comment by fbrier** [comment]
Perhaps I am not seeing this correctly, but isn't #515 about USB Passthrough?  [NWFilter](https://libvirt.org/formatnwfilter.html) is more of a firewall implemented on the host vs. the guest.

**Comment by pronix** [comment]
as soon as you will implement it - please sent pull request

**Comment by fbrier** [comment]
Not a problem.  I just got Vagrant up and running.  My Ruby is rudimentary.  I am just about to get my upgraded Chef Server 12 to work with Vagrant.  I'll need to learn the Provider API and this project's code base, but I will take a SWAG at it.  Thank you for this project!
