### ISSUE TITLE
Allow KVM to be hidden

### ISSUE THREAD

**Issue by darkengine-io** [pradels/vagrant-libvirt#527]
NVIDIA apparently does not like you running their cards in VM. This can be fixed by enabling the KVM hidden flag. See the documentation [here](https://libvirt.org/formatdomain.html#elementsFeatures).

It would be great to have the option to enable this flag so that NVIDIA cards can be used inside the VM.

**Comment by pronix** [comment]
you can use example https://github.com/pradels/vagrant-libvirt/pull/515 and implement required feature.
