### ISSUE TITLE
Configuring Domains to Autostart Upon Their Creation

### ISSUE THREAD

**Issue by ghost** [pradels/vagrant-libvirt#533]
Hello! I am unsure as to whether or not introducing this sort of feature as a mere domain option is currently under the radar. At the moment, I'm currently invoking the command `virsh autostart <domain>` to accomplish this very task, but it would be absolutely helpful to refer to a more native way to specify whether or not a domain should autostart. The following example is what I had in mind:

```ruby
guest.vm.provider 'libvirt' do |libvirt|
	libvirt.autostart = true
end
```

I simply wanted to throw this out there, just in case this idea hasn't yet been taken into consideration by anyone else using this project.

Thank you!

**Comment by infernix** [comment]
So this isn't definable in the XML, but:

```c

/*
 * call-seq:
 *   dom.autostart = [true|false]
 *
 * Call virDomainSetAutostart[http://www.libvirt.org/html/libvirt-libvirt.html#virDomainSetAutostart]
 * to make this domain autostart when libvirtd starts up.
  */
static VALUE libvirt_domain_autostart_equal(VALUE d, VALUE autostart)
{
    if (autostart != Qtrue && autostart != Qfalse) {
		rb_raise(rb_eTypeError,
                 "wrong argument type (expected TrueClass or FalseClass)");
    }

    ruby_libvirt_generate_call_nil(virDomainSetAutostart,
                                   ruby_libvirt_connect_get(d),
                                   ruby_libvirt_domain_get(d),
                                   RTEST(autostart) ? 1 : 0);
}
```

The best place to implement this that I can find would be in `action/start_domain.rb` - I'll see if I can work on a PR for this.
