### ISSUE TITLE
ERROR: Call to virStoragePoolDefineXML failed: operation failed: pool 'default' already exists

### ISSUE THREAD

**Issue by d33tah** [pradels/vagrant-libvirt#536]
```
# vagrant up
Vagrant.require_plugin is deprecated and has no effect any longer.
Use `vagrant plugin` commands to manage plugins. This warning will
be removed in the next version of Vagrant.
Bringing machine 'test_vm' up with 'libvirt' provider...
There was error while creating libvirt storage pool: Call to virStoragePoolDefineXML failed: operation failed: pool 'default' already exists with uuid 69266e1a-18f9-4e1f-98ed-d105ad8ba0d5
# vagrant --version
Vagrant 1.7.4
# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
```

**Comment by d33tah** [comment]
@pradels: Ping. Any chance this could be resolved?

**Comment by pronix** [comment]
no chance if you will not sent pull request.

**Comment by d33tah** [comment]
@pronix: hmm... I don't know libvirt enough to fix that. Is there any way you could help me debug that?

**Comment by pronix** [comment]
you can just rename default pool - it will created, or you should remove existed.

**Comment by d33tah** [comment]
That's interesting! `virsh` says that the pool isn't there and when I used --provider libvirt instead of exporting that, I got the machine up. Thanks @pronix!

**Comment by jcsmith** [comment]
I ran into this issue earlier this morning, it was caused by the default pool being defined but not active:

virsh # pool-list --all 
 Name                 State      Autostart 
-------------------------------------------
 default              inactive   no        
 Downloads            active     yes       
 ...

Activating the default pool resolved the issue:
virsh # pool-start default

**Comment by electrofelix** [comment]
Turns out there is a bug in fog-libvirt where it cannot retrieve info of inactive pools.

**Comment by spoutn1k** [comment]
Hey 8 years later this is still a thing

**Comment by red3nzo** [comment]
> Hey 8 years later this is still a thing

I was able to get it started using this command.

```rb
config.vm.provider :libvirt do |lib| 
  lib.storage_pool_name = "images"
end
```
libvirt seems to default to this `/var/lib/libvirt/images/` directory.

If you remove & uninit the `images` pool you may be able to override the name to something else.
