### ISSUE TITLE
synced_folder has no effect

### ISSUE THREAD

**Issue by Alukardd** [pradels/vagrant-libvirt#547]
Hello.

I try to use 9p, but I can't.

I wrote to Vagrantfile: ```config.vm.synced_folder "#{Dir.pwd}/flow", '/var/flow', type: '9p', accessmode: "mapped"```
But when I look at xml of running libvirt domain, I don't see any \<filesystem> tag at all.

How can I debug this situation?

```
vagrant 1.8.1
vagrant-libvirt 0.0.32
libvirt 1.2.9
```

When I run ```vagrant up --provider libvirt --debug```
```
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/synced_folders/rsync/plugin.rb
 INFO manager: Registered plugin: RSync synced folders
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/synced_folders/smb/plugin.rb
 INFO manager: Registered plugin: SMB synced folders
DEBUG global: Loading core plugin: /opt/vagrant/embedded/gems/gems/vagrant-1.8.1/plugins/synced_folders/nfs/plugin.rb
 INFO manager: Registered plugin: NFS synced folders
```
No 9p synced_folders I doesn't see.

**Comment by infernix** [comment]
I just tested this on latest master and it seemed to work fine:

```
...
==> nineptest: Should be mounting folders
==> nineptest:  /var/flow, opts: {:type=>:"9p", :accessmode=>"mapped", :guestpath=>"/var/flow", :hostpath=>"/tmp/9p/flow", :disabled=>false, :__vagrantfile=>true, :target=>"/var/flow", :mount=>true, :readonly=>nil, :mount_tag=>"8cf2e5c990e5dcd524151396039e52c"}
==> nineptest: Creating shared folders metadata...
...
==> nineptest: mounting p9 share in guest
==> nineptest: Rsyncing folder: /tmp/9p/ => /vagrant
...
```

Can you try with below Vagrantfile?

```
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
      config.vm.define "nineptest" do |ninep|
        ninep.vm.hostname = "nineptest"
        ninep.vm.box = "debian8jan2015libvirt"
        ninep.vm.box_url = "https://dx.infernix.net/debian8jan2015libvirt.box"
        ninep.vm.provider :libvirt do |v|
          v.memory = 512
          v.cpus = 1
        end
        ninep.vm.synced_folder "#{Dir.pwd}/flow", '/var/flow', type: '9p', accessmode: "mapped"
      end
end
```

Feel free to replace the box with a local debian box, but I did not have much luck with CentOS 7 (9p module not found in guest).

If it fails, please dump entire `vagrant -d up`  log here or in a pastebin link.

**Comment by dustymabe** [comment]
@infernix I don't think we enable 9p filesharing in RHEL (not recognized as stable) so that means it won't be in CentOS. 

@infernix @Alukardd There is an sshfs alternative that you might want to try https://github.com/dustymabe/vagrant-sshfs

**Comment by Alukardd** [comment]
Thanks, at this moment I suspended all my tasks related to this issue.

**Comment by infernix** [comment]
OK, since this is a distro issue I'm closing this; users of CentOS/RHEL that cannot use 9p with vagrant-libvirt will have to pick nfs or the aforementioned vagrant-sshfs, there's nothing to be done here by vagrant-libvirt.

**Comment by Alukardd** [comment]
I'm a Debian user...

**Comment by infernix** [comment]
Then please report the logs as requested in my comment so we can reopen this.

**Comment by Alukardd** [comment]
Sorry, not now. If I will return to this stack of software I will write in this issue.
