### ISSUE TITLE
vagrant folder not synced by default

### ISSUE THREAD

**Issue by bloody76** [pradels/vagrant-libvirt#557]
Hi,

I was having issues with the `/vagrant` folder that should be synced by default. But it seems it is not, if I try to write something in the VM, it won't be sync outside, and if I write something outside the VM it won't be sync inside.

here is the Vagrantfile I used:

```
$ cat Vagrantfile 
# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "rboyer/ubuntu-trusty64-libvirt"

  # Set the hostname
  config.vm.hostname = "dev-trusty64.vagrant"

  # Enable agent forwarding via SSH
  config.ssh.forward_agent = true

  config.vm.provider "libvirt" do |vb|
    vb.memory = 4000
    vb.cpus = 2
    vb.driver = 'qemu'
  end
end
```

My vagrant version is 1.7.2 though so maybe it's coming from that ? Are you experiencing the same thing ?

I also tried without the `vb.driver` option but it doesn't change anything.

Regards.

**Comment by infernix** [comment]
Depending on the host platform and guest OS you need to either use 9p or NFS if you want bidirectional sync to work.

Try this:
```ruby
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'libvirt'
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "rboyer/ubuntu-trusty64-libvirt"

  # Set the hostname
  config.vm.hostname = "dev-trusty64.vagrant"

  # Enable agent forwarding via SSH
  config.ssh.forward_agent = true

  config.vm.provider "libvirt" do |vb|
    vb.memory = 4000
    vb.cpus = 2
    vb.driver = 'qemu'
  end
  config.vm.synced_folder './', '/vagrant', type: 'nfs', nfs_udp: false, nfs_version: 4
end
```

Note that you will have to have `nfs` packages installed on the host. You'll also need to play with the nfs options depending on what your host can support, and you will need `sudo` to allow vagrant to edit your `/etc/exports` file.

If you can't use nfs, you can try `9p`,  [examples  are in the documentation](https://github.com/pradels/vagrant-libvirt#synced-folders)

**Comment by bloody76** [comment]
Hi,

Thank you for answering quickly :) Host is Linux (kernel 3.13) x86_64 arch and guest is ubuntu trusty64.

I already tried `9p` but it seems I can't write from the inside of the VM (permission denied) and if I put a owner it will throws an error (like in the issue #503) but this is another issue (any idea on that issue by the way ?).

For `nfs`, I can't let vagrant use `sudo`, it wouldn't be really a good practice, except if vagrant alone use it maybe.

Still, the `nfs` way seems to work, so I will see if I can use it.

Thank you for the details :)

**Comment by infernix** [comment]
If you can't allow sudo, you can predefine the exports on the host and pass `nfs_export: false`which should skip any actions that require root. [More info in the Vagrant docs](https://www.vagrantup.com/docs/synced-folders/nfs.html).
