### ISSUE TITLE
How to get more detail & solutions to resolve it about "libvirt: Waiting for domain to get an IP address..." ?

### ISSUE THREAD

**Issue by cmoulliard** [pradels/vagrant-libvirt#560]
```
INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::CreateNetworks:0x007f85808328b0>
 INFO create_networks: Using private at 172.28.128.0/24 as the management network nat is the mode
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::CreateNetworkInterfaces:0x007f85805ebcf0>
 INFO create_network_interfaces: Using private at 172.28.128.0/24 as the management network nat is the mode
 INFO create_network_interfaces: Creating network interface eth0 connected to network private.
 INFO create_network_interfaces: Creating network interface eth1 connected to network private.
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::SetBootOrder:0x007f85805a95d0>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::StartDomain:0x007f858051bf00>
 INFO interface: info: Starting domain.
 INFO interface: info: ==> libvirt: Starting domain.
==> libvirt: Starting domain.
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderLibvirt::Action::WaitTillUp:0x007f85804fdc58>
 INFO interface: info: Waiting for domain to get an IP address...
 INFO interface: info: ==> libvirt: Waiting for domain to get an IP address...
==> libvirt: Waiting for domain to get an IP address...
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
 INFO retryable: Retryable exception raised: #<Fog::Errors::TimeoutError: The specified wait_for timeout (2 seconds) was exceeded>
```

**Comment by infernix** [comment]
The Vagrant VM is supposed to issue a DHCP request which is answered by `dnsmasq`which `vagrant-libvirt` will use to connect to the VM by looking up the assigned IP in the hosts arp table. So in order:

1. Verify the VM actually issues a dhcp request
2. Verify that the `dnsmasq` daemon on the host is answering it
3. Verify that the assigned DHCP ip and VM mac address show up in`/proc/net/arp`

One way to check this is to use `wireshark` and check the traffic on the VMs nic; `brctl show` will tell you which NIC on the host (usually `vnetX`) is used by the VM; something like `tshark -i vnet0` should do the trick.

**Comment by cmoulliard** [comment]
I have resolved my problem as the service DHCP & dnsmasq weren't started on the host machine.

Question : Is it possible to avoid to use DHCP and to use a fix IP address (= 172.28.128.4) ?

**Comment by infernix** [comment]
Vagrant requires the use of `dnsmasq` to acquire an IP dynamically in order to execute initial provisioning. For static addressing, you can use `private_network` as described in [the documentation](https://github.com/pradels/vagrant-libvirt/#networks).

**Comment by ava-dylang** [comment]
does it work with dnsmaq-base?

**Comment by Isonyx** [comment]
@infernix What do I do if my machine is NOT issuing a DHCP request?
Using wireshark I find nothing. Also, will my global dnsmasq instance answer? Or does it have to be an instance started by Vargrant + libvirt

**Comment by seocliffdev** [comment]
I solved the problem by uncommenting line starts with ' config.vm.network' in **Vagrantfile**

**Comment by electrofelix** [comment]
@Haquor if the vm you bring up with vagrant doesn't issue a dhcp request for the default management network, you will have to use virt-manager to access the console, change the behaviour to attempt dhcp and repackage to a new box.
