### ISSUE TITLE
new volume creation fails

### ISSUE THREAD

**Issue by moozer** [pradels/vagrant-libvirt#580]
I have libvirt running nicely with kvm, and I want to get vagrant working again.

I installed vagrant 1.7.4 from the vagrant homepage and installed the plugin as instructed in the README. Then I did a "vagrant box add deb8_base <path to .box>"

When I do vagrant up I get a create volume error.
It wants to use /home/moz/VirtualMachines. 

Where does that path come from? 
In the past it has used /var/lib/libvirt/images (which is still the path for "default" pool).

Any pointers will be appreciated.

output below

```bash
$ vagrant up --provider=libvirt
Bringing machine 'default' up with 'libvirt' provider...
==> default: Uploading base box image as volume into libvirt storage...
/home/moz/.vagrant.d/gems/gems/fog-libvirt-0.0.4/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume_xml': Call to virStorageVolCreateXML failed: cannot chown /home/moz/VirtualMachines/deb8-base_vagrant_box_image_0.img to (0, 0): Operation not permitted (Libvirt::Error)
	from /home/moz/.vagrant.d/gems/gems/fog-libvirt-0.0.4/lib/fog/libvirt/requests/compute/create_volume.rb:6:in `create_volume'
	from /home/moz/.vagrant.d/gems/gems/fog-libvirt-0.0.4/lib/fog/libvirt/models/compute/volume.rb:40:in `save'
	from /home/moz/.vagrant.d/gems/gems/fog-core-1.36.0/lib/fog/core/collection.rb:51:in `create'
	from /home/moz/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/handle_box_image.rb:76:in `block in call'
	from /home/moz/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/handle_box_image.rb:60:in `synchronize'
	from /home/moz/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/handle_box_image.rb:60:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /home/moz/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/handle_storage_pool.rb:50:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /home/moz/.vagrant.d/gems/gems/vagrant-libvirt-0.0.32/lib/vagrant-libvirt/action/set_name_of_domain.rb:35:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in `lock'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'
```

**Comment by moozer** [comment]
I have made some progress

Previously I did not have to specify the libvirt.uri in Vagrantfile - it just defaulted to use libvirt on localhost. I had written 
    libvirt.uri="qemu:///session"
instead of 
    libvirt.uri="qemu:///system"

A [link](http://wiki.libvirt.org/page/FAQ#What_is_the_difference_between_qemu:.2F.2F.2Fsystem_and_qemu:.2F.2F.2Fsession.3F_Which_one_should_I_use.3F) for the next with that issues.

Now I must specify the uri, otherwise it defaults to 
    qemu://localhost/system?no_verify=1&keyfile=/home/moz/.ssh/id_rsa

For some reason
   virsh -c qemu://localhost/system
doesn't work, while
   virsh -c qemu:///system
works.

I am currently stuck at
    /home/moz/.vagrant.d/gems/gems/fog-core-1.36.0/lib/fog/core/service.rb:244:in `validate_options': Missing required arguments: libvirt_uri (ArgumentError)

and, as explained, I am specifying the libvirt uri.

Still, any suggestions are welcome.

Btw, I use debian/Testing, vagrant version 1.7.4 and vagrant-libvirt version 0.0.32

**Comment by moozer** [comment]
The validate_options error is known - see #568 
Downgrading to fog-libvirt version 0.0.3, solved that part.

Next issue was:

```bash
  $ vagrant up --provider=libvirt
  Bringing machine 'default' up with 'libvirt' provider...
  /home/moz/.vagrant.d/gems/gems/fog-libvirt-0.0.3/lib/fog/libvirt/requests/compute/list_volumes.rb:32:in `info': Call to virStorageVolGetInfo failed: Storage volume not found: no storage vol with matching path '/home/moz/.vagrant' (Libvirt::RetrieveError)
  ...
```

I solved this by simply 

```bash
$ mkdir ~/.vagrant
```

It now works for me, and I close it. It seems that my issues are fog-related, not vagrant-libvirt.

**Comment by lostinblue** [comment]
Umm, I believe you want it to be qemu:///session in almost every scenario, because that runs libvirt VMs as unprivileged user, any solution where you continue running as system is not desirable. Is there any solution to this issue that does not resolve itself by just giving the process super user privileges?

**Comment by moozer** [comment]
I had a lot of network issues, when I tried working with qemu:///session, so I am still on the qemu:///system solution.
Haven't looked at it recently though.

**Comment by lostinblue** [comment]
I have gotten mine to work perfectly outside of Vagrant, you just need to have qemu setup to bridge the connections or build your own unprivileged user structure.

I was hoping I could use vagrant to grammatically control my VM setup, but its unfortunate its built in specifically an insecure way.

**Comment by leseb** [comment]
@moozer how did you solve your `Call to virStorageVolCreateXML failed: cannot chown`?
Thanks!

**Comment by moozer** [comment]
As I recall it, that is one of the differences between using qemu:///session and qemu:///system.

As @lostinblue comments, one is run as an unprivileged process and the other as root - so "chown" issues sounds like a permissions issue that "root" would not encounter.

**Comment by leseb** [comment]
@moozer thanks for the quick response, I also use `qemu:///session` but now my `vagrant up` fails on  Call to virStorageVolCreateXML failed: cannot chown`...

**Comment by moozer** [comment]
qemu:///session is the unprivileged version, try using qemu:///system

Default values on my laptop:
```
> $ cat .vagrant.d/Vagrantfile 
# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.provider :libvirt do |libvirt|
    # otherwise it defaults to qemu://localhost/system?...
    libvirt.uri = "qemu:///system"
  end
  config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false
end

```

**Comment by leseb** [comment]
@moozer Thanks!

**Comment by electrofelix** [comment]
Technically it should be possible for vagrant-libvirt to use the correct user id or skip chown/chgrp as needed when using qemu:///session as long as the storage pool created is owned by the running user, but it does need some testing and experimentation to get right.

I believe Ubuntu still default to setting LIBVIRT_DEFAULT_URI="qemu:///system" via /etc/profile.d/ simply because all the kinks of using the user session haven't been ironed out.
