### ISSUE TITLE
Is it possible to bring up VMs across multiple physical machines?

### ISSUE THREAD

**Issue by 14msitaqadeer** [pradels/vagrant-libvirt#582]
Suppose i want to bring up 5 VMs with vagrant and i dont have enough resources on one physical machine, is there anyway that i can distribute my VMs across 2 or 3 physical machines?
If yes, then please guide me how could this be accomplished?

**Comment by infernix** [comment]
This is outside the scope of vagrant-libvirt, and vagrant is not designed for this so I highly doubt it would be a supported feature. 

Your best bet is to create multiple Vagrantfiles (one per host), configure private networking for all VMs. and then configuring the hosts and the network to allow for communication.

**Comment by 14msitaqadeer** [comment]
@infernix 
Thanks, your suggestion is valuable for me, for now i'll do this and will wait for a proper feature.
