### ISSUE TITLE
vagrant NFS timeout using mode => 'bridge' 

### ISSUE THREAD

**Issue by stephencooke** [pradels/vagrant-libvirt#588]
Since upgrading to  libvirt-1.2.17-13.el7_2.4.x86_64 / vagrant 1.8.1
from libvirt-1.2.8-16.el7_1.4.x86_64 / vagrant 1.7.2

$ sudo vagrant --version 
Vagrant 1.8.1
$ sudo vagrant plugin list
vagrant-libvirt (0.0.33)
vagrant-share (1.1.5, system)

vagrant up node1 --debug

When ran this  works with the NAT interface,  The failures start when it trys to use the other interface that doesnt work.

timeout on NFS

#<Vagrant::Errors::LinuxNFSMountFailed: The following SSH command responded with a non-zero exit status

LIBVIRT CONSOLE VIEW : 
When I investigated what was happening I found that the type of interface that was created inside libvirt provides a warning.

Network source : Direct 'br1'
	Source mode: Bridge
	
	Yellow Triangle : In most configurations, macvtop does not work for host to guest network communication
	

Vagrantfile : extract of the line that matters

 config.vm.define.vm.network :public_network, :\
 auto_config => 'false', :mode => 'bridge', \
 :dev => servers["public_dev"], :ip => servers["public_ip"], :netmask => servers["public_mask"]
 
ISSUE is that this :mode => 'bridge' no longer gives a working NIC for vagrant.  
  
Problem seems be that this defines the XML as this 
 
/etc/libvirt/qemu/node1.xml
 	
    <interface type='direct'>
      <mac address='XXXXXXXXXXXXXXX'/>
      <source dev='br1' mode='bridge'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </interface>
    
One solution : 

Network Source : change this "Bridge br1: Host device eno1"

    <interface type='bridge'>
      <mac address='XXXXXXXXXXXXXXX'/>
      <source bridge='br1'/>
      <model type='virtio'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </interface>

In the Vagrantfile change the following :mode => 'bridge' to :type => 'bridge'

 config.vm.define.vm.network :public_network, :  \
 auto_config => 'false', :type => 'bridge', :dev => servers["public_dev"], \
 :ip => servers["public_ip"], :netmask => servers["public_mask"]
 
This resolves the network issue, I posted this here as it caused me a great deal of reading to find a solution.

**Comment by infernix** [comment]
I agree this may not be trivial, but this is documented [here](https://github.com/pradels/vagrant-libvirt#public-network-options) and under Security Note [here](https://github.com/pradels/vagrant-libvirt#synced-folders).

It is worth considering doing some sanity checks when the NFS shared folder code is rewritten under #572  and #544.

If you want to improve the documentation please send a PR for the README :+1:
